<a href="https://colab.research.google.com/github/shishiradk/pytorch-pratices/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
import torch


# Create random tensor

tensor = torch.rand(7, 7)
print(tensor)
print(tensor.shape)


tensor([[0.8143, 0.3573, 0.2897, 0.8847, 0.3163, 0.5937, 0.7217],
        [0.2135, 0.7931, 0.1989, 0.4174, 0.2061, 0.3992, 0.2980],
        [0.1377, 0.5045, 0.9822, 0.9318, 0.7040, 0.5522, 0.4526],
        [0.6309, 0.2167, 0.7445, 0.5495, 0.8037, 0.6810, 0.9497],
        [0.2415, 0.9801, 0.1960, 0.4032, 0.6370, 0.0373, 0.8240],
        [0.6482, 0.4616, 0.7195, 0.4031, 0.8671, 0.0093, 0.0198],
        [0.3476, 0.1628, 0.0648, 0.5627, 0.2733, 0.2033, 0.8336]])
torch.Size([7, 7])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
x = torch.rand(1,7)
print(x)

# Perform matrix multiplication
y =torch.matmul(tensor,x.T)
print(y)

tensor([[0.0723, 0.6064, 0.0155, 0.1990, 0.6534, 0.1945, 0.2705]])
tensor([[0.9734],
        [0.8754],
        [1.2064],
        [1.2125],
        [1.3415],
        [0.9919],
        [0.6804]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
RANDOM_SEED =0
# torch.manual_seed(seed=RANDOM_SEED)

# Create two random tensors
random_tensor_C = torch.rand(3,4)
random_tensor_D = torch.rand(3,4)

# Matrix multiply tensors
y = torch.matmul(random_tensor_C,random_tensor_D.T)
y

tensor([[0.7656, 0.8134, 0.4103],
        [1.8788, 1.2471, 0.9134],
        [1.6740, 1.1996, 0.9446]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
RANDOM_SEED = 1234
torch.cuda.manual_seed(seed=RANDOM_SEED)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [16]:
import torch
# Set random seed
RANDOM_SEED = 1234

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
device

# Create two random tensors on GPU
y_on_gpu = torch.rand(2,3).to(device)
print(y_on_gpu)
print(y_on_gpu.shape)
tensor_on_gpu= torch.rand(2,4).to(device)
tensor_on_gpu


tensor([[0.1844, 0.4492, 0.9772],
        [0.2967, 0.5346, 0.1099]], device='cuda:0')
torch.Size([2, 3])


tensor([[0.3956, 0.1819, 0.6019, 0.1531],
        [0.0603, 0.1019, 0.3581, 0.9530]], device='cuda:0')


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [20]:
# Perform matmul on tensor_A and tensor_B
tensor_A = torch.rand(2,3)
tensor_B =torch.rand(3,2)

x=torch.matmul(tensor_A,tensor_B)
print(x)
x.shape


tensor([[1.1712, 1.0696],
        [0.9420, 0.8232]])


torch.Size([2, 2])

### 8. Find the maximum and minimum values of the output of 7.

In [22]:
import torch

x = torch.rand(7,7)
# Find max

max_value = torch.max(x)
print(max_value)

# Find min
min_value = torch.min(x)
print(min_value)

tensor(0.9647)
tensor(0.0365)


### 9. Find the maximum and minimum index values of the output of 7.

In [29]:
import torch

x = torch.rand(7,7)
# Find arg max
max_value = torch.argmax(x)

# Find arg min
min_value = torch.argmin(x)

max_coords = torch.unravel_index(max_value, x.shape)
min_coords = torch.unravel_index(min_value, x.shape)

print("\nMax value:", x[max_coords].item(), "at index", max_coords)
print("Min value:", x[min_coords].item(), "at index", min_coords)


Max value: 0.9950560927391052 at index (tensor(3), tensor(0))
Min value: 0.006496071815490723 at index (tensor(2), tensor(5))



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [30]:
import torch
# Set seed
RANDOM_SEED = 1234

# Create random tensor
x = torch.rand(2,3)

# Remove single dimensions
x = torch.squeeze(x)

# Print out tensors and their shapes
print(x)
x.shape

tensor([[0.4975, 0.8972, 0.8245],
        [0.4807, 0.4788, 0.3652]])


torch.Size([2, 3])