<a href="https://colab.research.google.com/github/shishiradk/pytorch-pratices/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!nvidia-smi


Sat Mar  8 11:04:22 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   41C    P8             11W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
print(torch.__version__)

2.5.1+cu124


introduction to tensors
creating tensor

In [4]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [5]:
scalar.ndim

0

In [6]:
#get tensor back as python int
scalar.item()

7

In [7]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#matrix
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
#TENSOR
TENSOR = torch.tensor([[[1,2,4],
                         [2,3,4],
                         [4,5,6]]])

In [15]:
TENSOR

tensor([[[1, 2, 4],
         [2, 3, 4],
         [4, 5, 6]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 4],
        [2, 3, 4],
        [4, 5, 6]])

In [19]:
TENSOR = torch.tensor([[[6,7,8],
                        [5,6,7],
                        [4,5,6]]])
TENSOR

tensor([[[6, 7, 8],
         [5, 6, 7],
         [4, 5, 6]]])

In [20]:
TENSOR.ndim

3

In [21]:
TENSOR.shape

torch.Size([1, 3, 3])

In [22]:
TENSOR[0]

tensor([[6, 7, 8],
        [5, 6, 7],
        [4, 5, 6]])

In [23]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(10,10,10)
random_tensor

tensor([[[0.9509, 0.1010, 0.9083, 0.5472, 0.2184, 0.1165, 0.4262, 0.5387,
          0.0030, 0.5919],
         [0.0847, 0.1732, 0.9978, 0.9351, 0.2783, 0.4567, 0.5747, 0.8300,
          0.0819, 0.1960],
         [0.4861, 0.1641, 0.7018, 0.3790, 0.7784, 0.5023, 0.2605, 0.1840,
          0.0319, 0.4925],
         [0.0966, 0.1649, 0.6757, 0.4083, 0.5208, 0.8876, 0.4596, 0.0659,
          0.9788, 0.7677],
         [0.8441, 0.7971, 0.4362, 0.5267, 0.8203, 0.3304, 0.0019, 0.9041,
          0.4418, 0.8249],
         [0.0197, 0.3053, 0.6890, 0.3223, 0.1924, 0.0183, 0.9526, 0.6264,
          0.9026, 0.2245],
         [0.9786, 0.8711, 0.4809, 0.1753, 0.9755, 0.6913, 0.0783, 0.5714,
          0.9924, 0.3412],
         [0.4938, 0.7792, 0.8648, 0.5429, 0.6799, 0.9000, 0.9100, 0.2728,
          0.5664, 0.5771],
         [0.5596, 0.4852, 0.3767, 0.1039, 0.6160, 0.6684, 0.6673, 0.0235,
          0.7921, 0.3928],
         [0.6777, 0.0717, 0.8538, 0.3668, 0.2004, 0.3943, 0.4146, 0.7490,
          0.1113,

In [24]:
random_tensor.ndim

3

In [25]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224))#height,width,color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [26]:
torch.rand(3,3)

tensor([[0.2121, 0.4185, 0.6404],
        [0.4565, 0.1690, 0.9061],
        [0.7295, 0.1798, 0.7128]])

In [27]:
#zeros and ones
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
#create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [29]:
#use torch.range()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
one_to_ten.shape

torch.Size([10])

In [32]:
ten_zero = torch.zeros_like(input=one_to_ten)
ten_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor Datatype

**Note:** Tensor datatype is one of the 3 big errors you'll run into with PyTorch & deep learning:

1. Tensors not right datatype

2.Tensor not right shape

In [33]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [34]:
tensor = torch.tensor( [1.0, 2.0, 3.0],dtype=torch.float32)
print(tensor)


tensor([1., 2., 3.])


In [35]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [36]:
float_16_tensor = float_32_tensor

In [37]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [38]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [39]:
#create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0062, 0.6610, 0.6065, 0.1179],
        [0.7041, 0.5144, 0.0986, 0.5549],
        [0.1296, 0.4288, 0.7601, 0.7368]])

In [40]:
#find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.0062, 0.6610, 0.6065, 0.1179],
        [0.7041, 0.5144, 0.0986, 0.5549],
        [0.1296, 0.4288, 0.7601, 0.7368]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


###manipulating Tensors ( tensor operation)

Tensor operattion include:

*Addition

*Subtraction

*Multiplication(element-wise)

*division

*Matrix Multiplication

In [41]:
#create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [42]:
#multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [43]:
tensor

tensor([1, 2, 3])

In [44]:
#subtract
tensor - 10

tensor([-9, -8, -7])

In [45]:
#divide
tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [46]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [47]:
torch.add(tensor,10)

tensor([11, 12, 13])

Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1.Element-wise multiplication

2.Matrix multiplication(dot product)

There are two main rules that performing matrix multiplication

1. The **inner dimensions** must match:

 *(3,2) @ (3,2) won't work

 *(2,3) @ (3,2) will work

 *(3,2) @ (2,3) will work


2.The resulting matrix has the shape of the **outer dimension**:

*(2,3) @ (3,2) -> (2,2)

*(3,2) 2 (2,3) -. (3,3)




In [56]:
torch.matmul(torch.rand(10,10),torch.rand(10,10))

tensor([[2.9306, 2.8030, 2.2437, 2.3184, 3.1537, 1.6902, 3.1911, 3.7811, 1.8827,
         2.5652],
        [2.4935, 2.7076, 2.3155, 2.5190, 3.8402, 1.6430, 2.8575, 3.6796, 1.7858,
         2.4411],
        [2.4701, 2.9059, 2.2529, 3.0286, 3.7816, 1.6010, 2.8200, 4.0167, 2.1772,
         2.6022],
        [2.4734, 2.6251, 1.8248, 1.8711, 3.2096, 1.4459, 2.7852, 3.3484, 1.7481,
         2.1868],
        [2.8054, 2.8948, 2.1124, 2.5580, 3.8080, 1.6525, 3.1301, 4.0559, 1.9702,
         2.7018],
        [2.4628, 2.3384, 2.0044, 2.1869, 3.4056, 1.0915, 2.6867, 3.6090, 1.4370,
         2.2819],
        [2.1048, 2.9231, 1.9609, 2.1423, 3.7587, 1.3624, 2.3800, 3.3381, 1.8146,
         2.5519],
        [2.8496, 2.8958, 3.1188, 2.9829, 3.9142, 2.3595, 3.7586, 4.5629, 2.2828,
         2.9488],
        [2.3148, 2.8381, 2.4403, 2.2648, 3.9331, 1.8418, 3.0600, 3.7919, 1.9868,
         2.5255],
        [2.5494, 1.8128, 2.1187, 2.3035, 2.9550, 1.5696, 2.5347, 3.2087, 1.6333,
         1.8267]])

In [48]:
#Elementwise multiplication
print(tensor,"*",tensor)
print(f"Equals:{tensor * tensor}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [49]:
#matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [50]:
#matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [52]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
  print(value)



tensor(1)
tensor(5)
tensor(14)
CPU times: user 1.33 ms, sys: 0 ns, total: 1.33 ms
Wall time: 1.42 ms


In [54]:
tensor @ tensor

tensor(14)

In [53]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 948 µs, sys: 0 ns, total: 948 µs
Wall time: 714 µs


tensor(14)

### one of the most common errors in deep learning: shape errors