<a href="https://colab.research.google.com/github/shishiradk/pytorch-pratices/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [73]:
!nvidia-smi


Sun Aug 24 03:37:12 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   39C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [74]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
print(torch.__version__)

2.8.0+cu126


introduction to tensors
creating tensor

In [75]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [76]:
scalar.ndim

0

In [77]:
#get tensor back as python int
scalar.item()

7

In [78]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [79]:
vector.ndim

1

In [80]:
vector.shape

torch.Size([2])

In [81]:
#matrix
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [82]:
MATRIX.ndim

2

In [83]:
MATRIX[1]

tensor([ 9, 10])

In [84]:
MATRIX.shape

torch.Size([2, 2])

In [85]:
#TENSOR
TENSOR = torch.tensor([[[1,2,4],
                         [2,3,4],
                         [4,5,6]]])

In [86]:
TENSOR

tensor([[[1, 2, 4],
         [2, 3, 4],
         [4, 5, 6]]])

In [87]:
TENSOR.ndim

3

In [88]:
TENSOR.shape

torch.Size([1, 3, 3])

In [89]:
TENSOR[0]

tensor([[1, 2, 4],
        [2, 3, 4],
        [4, 5, 6]])

In [90]:
TENSOR = torch.tensor([[[6,7,8],
                        [5,6,7],
                        [4,5,6]]])
TENSOR

tensor([[[6, 7, 8],
         [5, 6, 7],
         [4, 5, 6]]])

In [91]:
TENSOR.ndim

3

In [92]:
TENSOR.shape

torch.Size([1, 3, 3])

In [93]:
TENSOR[0]

tensor([[6, 7, 8],
        [5, 6, 7],
        [4, 5, 6]])

In [94]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(10,10,10)
random_tensor

tensor([[[1.1330e-01, 4.4635e-01, 4.5589e-01, 3.5026e-01, 9.2456e-01,
          3.2796e-01, 6.8752e-01, 8.5322e-01, 8.2704e-01, 1.0302e-01],
         [6.0384e-01, 3.7614e-01, 6.9420e-02, 5.0136e-01, 8.3909e-01,
          8.4769e-01, 9.2319e-01, 4.2433e-01, 2.8893e-01, 1.6201e-01],
         [5.3473e-01, 7.3857e-01, 5.4894e-01, 4.2869e-01, 6.4818e-01,
          2.2247e-02, 5.1205e-03, 5.1873e-01, 4.9536e-01, 6.3689e-01],
         [3.8759e-01, 4.4185e-02, 4.0849e-01, 7.1307e-01, 9.9050e-01,
          4.0908e-01, 7.3192e-01, 3.5860e-01, 2.4347e-01, 8.9913e-01],
         [2.3948e-01, 4.6481e-02, 2.6360e-01, 8.3300e-01, 6.8007e-01,
          7.3169e-01, 8.4832e-01, 6.5081e-01, 2.3814e-01, 5.4152e-02],
         [2.9380e-01, 9.2912e-04, 5.9171e-01, 5.0135e-02, 3.6381e-01,
          8.0526e-01, 9.9486e-01, 2.5747e-01, 7.3672e-01, 1.1417e-01],
         [1.4851e-01, 5.2231e-01, 7.9803e-01, 1.3420e-01, 7.2724e-01,
          4.6701e-01, 1.4614e-01, 4.5198e-01, 5.6975e-02, 4.5971e-01],
         [1.1

In [95]:
random_tensor.ndim

3

In [96]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224))#height,width,color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [97]:
torch.rand(3,3)

tensor([[0.6335, 0.5542, 0.4855],
        [0.7743, 0.2988, 0.3186],
        [0.1139, 0.2638, 0.5980]])

In [98]:
#zeros and ones
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [99]:
#create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [100]:
#use torch.range()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [102]:
one_to_ten.shape

torch.Size([10])

In [103]:
ten_zero = torch.zeros_like(input=one_to_ten)
ten_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor Datatype

**Note:** Tensor datatype is one of the 3 big errors you'll run into with PyTorch & deep learning:

1. Tensors not right datatype

2.Tensor not right shape

In [104]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [105]:
tensor = torch.tensor( [1.0, 2.0, 3.0],dtype=torch.float32)
print(tensor)


tensor([1., 2., 3.])


In [106]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [107]:
float_16_tensor = float_32_tensor

In [108]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [109]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [110]:
#create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3517, 0.5385, 0.7524, 0.8155],
        [0.6625, 0.1944, 0.2155, 0.5900],
        [0.7634, 0.2097, 0.7094, 0.5921]])

In [111]:
#find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3517, 0.5385, 0.7524, 0.8155],
        [0.6625, 0.1944, 0.2155, 0.5900],
        [0.7634, 0.2097, 0.7094, 0.5921]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


###manipulating Tensors ( tensor operation)

Tensor operattion include:

*Addition

*Subtraction

*Multiplication(element-wise)

*division

*Matrix Multiplication

In [112]:
#create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [113]:
#multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [114]:
tensor

tensor([1, 2, 3])

In [115]:
#subtract
tensor - 10

tensor([-9, -8, -7])

In [116]:
#divide
tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [117]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [118]:
torch.add(tensor,10)

tensor([11, 12, 13])

Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1.Element-wise multiplication

2.Matrix multiplication(dot product)

There are two main rules that performing matrix multiplication

1. The **inner dimensions** must match:

 *(3,2) @ (3,2) won't work

 *(2,3) @ (3,2) will work

 *(3,2) @ (2,3) will work


2.The resulting matrix has the shape of the **outer dimension**:

*(2,3) @ (3,2) -> (2,2)

*(3,2) 2 (2,3) -. (3,3)




In [119]:
torch.matmul(torch.rand(10,10),torch.rand(10,10))

tensor([[4.1784, 2.1985, 3.5419, 2.6051, 2.5129, 2.9512, 3.0397, 2.6946, 3.0555,
         2.3982],
        [3.9941, 2.5178, 4.0471, 2.6102, 2.8502, 3.0964, 2.6626, 2.0042, 3.5470,
         2.6322],
        [2.5123, 1.5256, 2.7509, 1.7273, 1.4141, 1.8743, 2.0356, 2.1446, 1.8119,
         1.4534],
        [3.6664, 1.8978, 3.7587, 2.2403, 2.3875, 2.5574, 2.6403, 2.2373, 2.6510,
         2.3957],
        [2.9778, 2.0097, 2.9512, 1.9313, 1.9372, 2.4347, 2.1699, 2.0608, 2.3971,
         1.9751],
        [2.4188, 1.5737, 1.9795, 1.2099, 1.7054, 2.0677, 1.7978, 1.7356, 1.8428,
         1.3994],
        [3.9900, 3.1668, 4.2683, 2.6209, 2.9230, 3.4143, 2.9342, 2.1285, 3.9609,
         2.8096],
        [3.2842, 1.7330, 3.2807, 1.8960, 2.1878, 2.3791, 2.3748, 2.2066, 2.2191,
         2.1541],
        [3.8173, 2.1393, 3.4205, 2.2787, 2.4771, 2.6680, 2.5974, 2.0308, 2.8522,
         2.6092],
        [2.2962, 1.3557, 2.4084, 1.6769, 1.5445, 1.7046, 1.8694, 1.4486, 2.0257,
         1.2822]])

In [120]:
#Elementwise multiplication
print(tensor,"*",tensor)
print(f"Equals:{tensor * tensor}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [121]:
#matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [122]:
#matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [123]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
  print(value)



tensor(1)
tensor(5)
tensor(14)
CPU times: user 23 µs, sys: 887 µs, total: 910 µs
Wall time: 921 µs


In [124]:
tensor @ tensor

tensor(14)

In [125]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 37 µs, sys: 5 µs, total: 42 µs
Wall time: 44.8 µs


tensor(14)

### one of the most common errors in deep learning: shape errors

In [126]:
 #Shape for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])


#torch.mm(tensor_A,tensor_B) #torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A, tensor_B.T)


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [127]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor tensor

In [128]:
tensor_B,tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [129]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [130]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape} , tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying : {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
torch.matmul(tensor_A, tensor_B.T)

Original shapes: tensor_A = torch.Size([3, 2]) , tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying : torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [131]:
print(f"Original shapes : tensor_A = {tensor_A.shape} ,tensor_B = {tensor_B.shape}")
print(f"New shapes:tensorA.T = {tensor_A.shape} (same shape as above), tensor_B = {tensor_B.T.shape}")
print(f"Multiplying : {tensor_A.T.shape} @ {tensor_B.shape} <- inner dimension must match")
print("Output:\n")
out = torch.matmul(tensor_A.T, tensor_B)
print(output)

Original shapes : tensor_A = torch.Size([3, 2]) ,tensor_B = torch.Size([3, 2])
New shapes:tensorA.T = torch.Size([3, 2]) (same shape as above), tensor_B = torch.Size([2, 3])
Multiplying : torch.Size([2, 3]) @ torch.Size([3, 2]) <- inner dimension must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


Finding the min ,max , mean, sum,etc (tensor aggregation)

In [132]:
#create a tensor
x= torch.arange(1,100,10)
x , x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [133]:
# Find the main
torch.min(x) , x.min()

(tensor(1), tensor(1))

In [134]:
#Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)) ,x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [135]:
#find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min max

In [136]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [137]:
# find the position that has the min value with argminn() -> returns index position of the target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [139]:
#find the position in tensor that has the maximum value with argmax
x.argmax()

tensor(9)

In [140]:
x[9]

tensor(91)

# reshaping ,stacking , squeezing and unsquezzing tensore

* Reshaping - reshape an input tensor to a defined shape

* view  - return a view of an input tensor of certain shape but keep the same memory as the original tensor

* stacking - combine muultiple tensors on top of each other (vstack) or side by side (hstack)

* squeeze - remove all dimension from a tensor

* unsqueeze - add a dimension to a target tensor

* permute - return a view of the input with dimension permute(swapped) in a certain way

In [153]:
# lets create a tesor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [154]:
# add a extra dimension
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [155]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [156]:
#changing z changes x ( because a view of a tensor shares the saame memory as the original input)
z[:,0] =5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [167]:
# stack tensors on top of eachother
x_stacked = torch.stack([x,x,x,x],dim=0 )
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])