<a href="https://colab.research.google.com/github/shishiradk/pytorch-pratices/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [181]:
!nvidia-smi


Sun Aug 24 04:08:56 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   37C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [182]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
print(torch.__version__)

2.8.0+cu126


introduction to tensors
creating tensor

In [183]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [184]:
scalar.ndim

0

In [185]:
#get tensor back as python int
scalar.item()

7

In [186]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [187]:
vector.ndim

1

In [188]:
vector.shape

torch.Size([2])

In [189]:
#matrix
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [190]:
MATRIX.ndim

2

In [191]:
MATRIX[1]

tensor([ 9, 10])

In [192]:
MATRIX.shape

torch.Size([2, 2])

In [193]:
#TENSOR
TENSOR = torch.tensor([[[1,2,4],
                         [2,3,4],
                         [4,5,6]]])

In [194]:
TENSOR

tensor([[[1, 2, 4],
         [2, 3, 4],
         [4, 5, 6]]])

In [195]:
TENSOR.ndim

3

In [196]:
TENSOR.shape

torch.Size([1, 3, 3])

In [197]:
TENSOR[0]

tensor([[1, 2, 4],
        [2, 3, 4],
        [4, 5, 6]])

In [198]:
TENSOR = torch.tensor([[[6,7,8],
                        [5,6,7],
                        [4,5,6]]])
TENSOR

tensor([[[6, 7, 8],
         [5, 6, 7],
         [4, 5, 6]]])

In [199]:
TENSOR.ndim

3

In [200]:
TENSOR.shape

torch.Size([1, 3, 3])

In [201]:
TENSOR[0]

tensor([[6, 7, 8],
        [5, 6, 7],
        [4, 5, 6]])

In [202]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(10,10,10)
random_tensor

tensor([[[0.3464, 0.5311, 0.1786, 0.8315, 0.2647, 0.1120, 0.8697, 0.4339,
          0.5210, 0.3205],
         [0.9373, 0.7788, 0.0065, 0.6029, 0.4733, 0.4155, 0.8211, 0.7446,
          0.0295, 0.8929],
         [0.6946, 0.7601, 0.4400, 0.5831, 0.3633, 0.3809, 0.0530, 0.8394,
          0.5716, 0.5299],
         [0.2009, 0.3150, 0.3439, 0.8397, 0.7445, 0.8814, 0.6995, 0.9077,
          0.6609, 0.3849],
         [0.7533, 0.2504, 0.3460, 0.9711, 0.4800, 0.0064, 0.1411, 0.0795,
          0.0048, 0.5585],
         [0.3238, 0.9623, 0.6053, 0.5894, 0.1389, 0.5668, 0.6751, 0.9231,
          0.9592, 0.1806],
         [0.9285, 0.4112, 0.4884, 0.2840, 0.7645, 0.7092, 0.0832, 0.7557,
          0.0180, 0.8804],
         [0.6558, 0.2811, 0.3805, 0.2868, 0.1786, 0.4671, 0.5768, 0.7294,
          0.2742, 0.8646],
         [0.8709, 0.4262, 0.0171, 0.2222, 0.9701, 0.0343, 0.3836, 0.9029,
          0.0066, 0.9329],
         [0.7506, 0.9747, 0.4588, 0.4578, 0.7278, 0.4342, 0.1249, 0.6629,
          0.8775,

In [203]:
random_tensor.ndim

3

In [204]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224))#height,width,color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [205]:
torch.rand(3,3)

tensor([[0.6598, 0.4768, 0.4964],
        [0.4904, 0.1516, 0.4927],
        [0.0775, 0.8393, 0.5194]])

In [206]:
#zeros and ones
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [207]:
#create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [208]:
#use torch.range()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [209]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [210]:
one_to_ten.shape

torch.Size([10])

In [211]:
ten_zero = torch.zeros_like(input=one_to_ten)
ten_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor Datatype

**Note:** Tensor datatype is one of the 3 big errors you'll run into with PyTorch & deep learning:

1. Tensors not right datatype

2.Tensor not right shape

In [212]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [213]:
tensor = torch.tensor( [1.0, 2.0, 3.0],dtype=torch.float32)
print(tensor)


tensor([1., 2., 3.])


In [214]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [215]:
float_16_tensor = float_32_tensor

In [216]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [217]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [218]:
#create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.1470, 0.7070, 0.9250, 0.9558],
        [0.8333, 0.3290, 0.2520, 0.1678],
        [0.7975, 0.1895, 0.2780, 0.1463]])

In [219]:
#find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.1470, 0.7070, 0.9250, 0.9558],
        [0.8333, 0.3290, 0.2520, 0.1678],
        [0.7975, 0.1895, 0.2780, 0.1463]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


###manipulating Tensors ( tensor operation)

Tensor operattion include:

*Addition

*Subtraction

*Multiplication(element-wise)

*division

*Matrix Multiplication

In [220]:
#create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [221]:
#multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [222]:
tensor

tensor([1, 2, 3])

In [223]:
#subtract
tensor - 10

tensor([-9, -8, -7])

In [224]:
#divide
tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [225]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [226]:
torch.add(tensor,10)

tensor([11, 12, 13])

Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1.Element-wise multiplication

2.Matrix multiplication(dot product)

There are two main rules that performing matrix multiplication

1. The **inner dimensions** must match:

 *(3,2) @ (3,2) won't work

 *(2,3) @ (3,2) will work

 *(3,2) @ (2,3) will work


2.The resulting matrix has the shape of the **outer dimension**:

*(2,3) @ (3,2) -> (2,2)

*(3,2) 2 (2,3) -. (3,3)




In [227]:
torch.matmul(torch.rand(10,10),torch.rand(10,10))

tensor([[2.2904, 2.8910, 3.2229, 1.9978, 1.6274, 2.9663, 3.0811, 3.3842, 3.1104,
         3.5026],
        [2.7434, 3.5701, 3.7881, 2.4889, 2.4290, 3.9522, 3.2730, 3.4718, 3.1095,
         3.3899],
        [1.7432, 1.9586, 2.2192, 1.1629, 1.0329, 2.4047, 1.6925, 1.8595, 1.6481,
         2.1615],
        [2.2838, 3.4345, 3.4670, 2.2343, 2.0836, 2.8813, 2.8763, 3.3309, 2.7660,
         3.2441],
        [1.7898, 2.5229, 2.2429, 1.2845, 1.1381, 2.1460, 2.0867, 2.3885, 1.6193,
         2.3818],
        [2.6784, 3.6033, 3.7279, 1.9430, 1.6743, 3.0160, 2.9251, 3.5911, 2.8324,
         3.8805],
        [1.6663, 1.9917, 2.1264, 1.5867, 1.4706, 2.6244, 1.6946, 1.6915, 1.9172,
         2.1744],
        [2.1795, 2.2568, 2.9271, 1.5762, 1.3600, 2.4204, 2.4523, 2.5087, 2.0326,
         2.8092],
        [2.5081, 2.8308, 3.0987, 1.9026, 1.8994, 3.4353, 2.7265, 2.8327, 2.3707,
         2.9946],
        [1.3873, 2.2922, 1.8276, 1.4150, 1.2337, 2.3254, 1.7965, 1.9500, 1.5157,
         2.1237]])

In [228]:
#Elementwise multiplication
print(tensor,"*",tensor)
print(f"Equals:{tensor * tensor}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [229]:
#matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [230]:
#matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [231]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
  print(value)



tensor(1)
tensor(5)
tensor(14)
CPU times: user 986 µs, sys: 73 µs, total: 1.06 ms
Wall time: 1.17 ms


In [232]:
tensor @ tensor

tensor(14)

In [233]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 30 µs, sys: 2 µs, total: 32 µs
Wall time: 35 µs


tensor(14)

### one of the most common errors in deep learning: shape errors

In [234]:
 #Shape for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])


#torch.mm(tensor_A,tensor_B) #torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A, tensor_B.T)


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [235]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor tensor

In [236]:
tensor_B,tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [237]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [238]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape} , tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying : {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
torch.matmul(tensor_A, tensor_B.T)

Original shapes: tensor_A = torch.Size([3, 2]) , tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying : torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [239]:
print(f"Original shapes : tensor_A = {tensor_A.shape} ,tensor_B = {tensor_B.shape}")
print(f"New shapes:tensorA.T = {tensor_A.shape} (same shape as above), tensor_B = {tensor_B.T.shape}")
print(f"Multiplying : {tensor_A.T.shape} @ {tensor_B.shape} <- inner dimension must match")
print("Output:\n")
out = torch.matmul(tensor_A.T, tensor_B)
print(output)

Original shapes : tensor_A = torch.Size([3, 2]) ,tensor_B = torch.Size([3, 2])
New shapes:tensorA.T = torch.Size([3, 2]) (same shape as above), tensor_B = torch.Size([2, 3])
Multiplying : torch.Size([2, 3]) @ torch.Size([3, 2]) <- inner dimension must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


Finding the min ,max , mean, sum,etc (tensor aggregation)

In [240]:
#create a tensor
x= torch.arange(1,100,10)
x , x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [241]:
# Find the main
torch.min(x) , x.min()

(tensor(1), tensor(1))

In [242]:
#Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)) ,x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [243]:
#find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min max

In [244]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [245]:
# find the position that has the min value with argminn() -> returns index position of the target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [246]:
#find the position in tensor that has the maximum value with argmax
x.argmax()

tensor(9)

In [247]:
x[9]

tensor(91)

# reshaping ,stacking , squeezing and unsquezzing tensore

* Reshaping - reshape an input tensor to a defined shape

* view  - return a view of an input tensor of certain shape but keep the same memory as the original tensor

* stacking - combine muultiple tensors on top of each other (vstack) or side by side (hstack)

* squeeze - remove all dimension from a tensor

* unsqueeze - add a dimension to a target tensor

* permute - return a view of the input with dimension permute(swapped) in a certain way

In [248]:
# lets create a tesor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [249]:
# add a extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [250]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [251]:
#changing z changes x ( because a view of a tensor shares the saame memory as the original input)
z[:,0] =5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [252]:
# stack tensors on top of eachother
x_stacked = torch.stack([x,x,x,x],dim=0 )
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

squeeze

In [270]:
#tourch.squeeze() -- remove  all single dimensions from a target tensor
print(f"previous tensor: {x_reshaped}")
print(f"previous shape: {x_reshaped.shape}")

#remove extra dimension from x_shaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew  tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
previous shape: torch.Size([1, 9])

New  tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [272]:
#tourch.unsqueeze() -- remove  all single dimensions from a target tensor
print(f"previous target: {x_squeezed}")
print(f"previous shape: {x_squeezed.shape}")

#add extra dimension from x_shaped
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew  tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape: torch.Size([9])

New  tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [274]:
#torch.permute - reaarabges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) #[height,width,color_channels]

# permute the original tensor to rearrange the axis (or dim) oredr
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2,2->0

print(f"previous shape: {x_original.shape}")
print(f"new shape: {x_permuted.shape}") #[color_channel,height,width]

previous shape: torch.Size([224, 224, 3])
new shape: torch.Size([3, 224, 224])


In [280]:
x_original[0,0,0] = 728218
x_original[0,0,0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

## Indexing (selecting data from tensors)

Indexing with Pytorch is similar to indexing with numpy

In [282]:
# create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [283]:
# lets a index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [286]:
#lets index in middle bracket
x[0,0]
#x[0][0]

tensor([1, 2, 3])

In [290]:
# Lets index on the most innefr barcket (last dimension)
x[0][1][1]

tensor(5)

In [291]:
# you can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [292]:
# get all values of 0th and 1st dimension but only index 1 of the 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [293]:
# get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [294]:
# get index o of 0th 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [303]:
# index on x to return 9
x[0,2,2]



tensor(9)

In [306]:
# index on x to return 3
x[0,0,2]


tensor(3)

In [308]:
# index on x return 6
x[0,1,2]

tensor(6)