<a href="https://colab.research.google.com/github/shishiradk/pytorch-pratices/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi


Tue Mar  4 12:24:09 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   46C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
print(torch.__version__)

2.5.1+cu124


introduction to tensors
creating tensor

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get tensor back as python int
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#matrix
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2,4],
                         [2,3,4],
                         [4,5,6]]])

In [ ]:
TENSOR

tensor([[[1, 2, 4],
         [2, 3, 4],
         [4, 5, 6]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 4],
        [2, 3, 4],
        [4, 5, 6]])

In [ ]:
TENSOR = torch.tensor([[[6,7,8],
                        [5,6,7],
                        [4,5,6]]])
TENSOR

tensor([[[6, 7, 8],
         [5, 6, 7],
         [4, 5, 6]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[6, 7, 8],
        [5, 6, 7],
        [4, 5, 6]])

In [ ]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(10,10,10)
random_tensor

tensor([[[4.6204e-01, 5.0122e-01, 8.6299e-02, 3.5146e-01, 6.3505e-01,
          6.2549e-01, 7.9843e-01, 7.1115e-01, 8.7762e-01, 3.7998e-02],
         [7.3859e-01, 3.6245e-01, 9.5571e-01, 6.5085e-01, 3.7049e-01,
          6.0646e-01, 1.3793e-01, 6.2164e-01, 9.4633e-01, 8.3404e-01],
         [9.4869e-01, 6.6297e-02, 4.6324e-01, 1.8685e-01, 4.2261e-01,
          4.0034e-01, 1.5210e-01, 1.8450e-01, 4.3258e-01, 1.9778e-01],
         [7.9423e-01, 6.2073e-01, 9.9926e-01, 1.5821e-02, 8.6652e-01,
          8.6125e-01, 6.1917e-01, 4.9897e-01, 9.2897e-01, 2.8309e-01],
         [4.1722e-01, 2.3067e-01, 4.8770e-01, 2.2708e-01, 4.7589e-01,
          2.9905e-01, 8.1846e-01, 6.1096e-01, 3.1234e-01, 8.5788e-01],
         [5.2251e-01, 2.1302e-01, 6.9448e-01, 7.2929e-01, 9.5391e-01,
          4.3250e-01, 1.1200e-01, 2.4687e-01, 4.4514e-01, 2.3959e-01],
         [8.0358e-03, 3.9038e-01, 8.8240e-01, 6.0442e-01, 3.0426e-01,
          3.8092e-01, 7.4172e-01, 9.9658e-01, 6.0201e-01, 8.6560e-01],
         [5.8

In [ ]:
random_tensor.ndim

3

In [ ]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224))#height,width,color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [ ]:
torch.rand(3,3)

tensor([[0.8359, 0.3786, 0.7404],
        [0.5603, 0.2086, 0.7561],
        [0.7007, 0.0215, 0.8261]])

In [ ]:
#zeros and ones
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
#use torch.range()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
one_to_ten.shape

torch.Size([10])