<a href="https://colab.research.google.com/github/shishiradk/pytorch-pratices/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi


Sun Aug 24 15:26:13 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   38C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
print(torch.__version__)

2.8.0+cu126


introduction to tensors
creating tensor

In [3]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#get tensor back as python int
scalar.item()

7

In [6]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#matrix
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
#TENSOR
TENSOR = torch.tensor([[[1,2,4],
                         [2,3,4],
                         [4,5,6]]])

In [14]:
TENSOR

tensor([[[1, 2, 4],
         [2, 3, 4],
         [4, 5, 6]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 4],
        [2, 3, 4],
        [4, 5, 6]])

In [18]:
TENSOR = torch.tensor([[[6,7,8],
                        [5,6,7],
                        [4,5,6]]])
TENSOR

tensor([[[6, 7, 8],
         [5, 6, 7],
         [4, 5, 6]]])

In [19]:
TENSOR.ndim

3

In [20]:
TENSOR.shape

torch.Size([1, 3, 3])

In [21]:
TENSOR[0]

tensor([[6, 7, 8],
        [5, 6, 7],
        [4, 5, 6]])

In [22]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(10,10,10)
random_tensor

tensor([[[5.7550e-01, 4.5093e-02, 6.8720e-01, 5.7020e-02, 9.5705e-01,
          2.9283e-01, 8.6465e-01, 1.0291e-01, 3.2324e-01, 2.6413e-01],
         [4.9297e-01, 7.2683e-01, 9.0800e-01, 4.6047e-01, 6.8272e-01,
          3.6446e-01, 7.4832e-01, 7.8866e-01, 2.3395e-01, 7.3103e-01],
         [1.0993e-01, 4.0733e-01, 6.6442e-01, 6.9226e-01, 9.6865e-01,
          8.1960e-01, 9.0238e-01, 4.7101e-01, 3.6360e-01, 8.4552e-01],
         [1.6768e-01, 7.2243e-01, 1.0726e-01, 6.6389e-01, 6.7674e-01,
          3.7285e-01, 4.0794e-01, 7.4589e-01, 3.2540e-01, 4.1444e-01],
         [1.8730e-01, 2.8359e-02, 5.6609e-02, 6.2324e-01, 9.7967e-01,
          8.8517e-01, 3.6316e-01, 6.7726e-01, 9.0249e-02, 4.6142e-02],
         [8.8352e-01, 6.3333e-01, 9.2006e-01, 4.6528e-02, 1.5645e-01,
          5.1789e-01, 3.2446e-01, 3.2744e-01, 7.9085e-01, 9.8015e-01],
         [8.7790e-01, 9.7277e-01, 5.9813e-01, 4.4446e-01, 2.9267e-01,
          4.0540e-01, 2.5522e-01, 5.2186e-01, 5.6800e-01, 5.8625e-01],
         [9.8

In [23]:
random_tensor.ndim

3

In [24]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224))#height,width,color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [25]:
torch.rand(3,3)

tensor([[0.6136, 0.1237, 0.2926],
        [0.6663, 0.2218, 0.2250],
        [0.3787, 0.6211, 0.9056]])

In [26]:
#zeros and ones
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
#create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
#use torch.range()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
one_to_ten.shape

torch.Size([10])

In [31]:
ten_zero = torch.zeros_like(input=one_to_ten)
ten_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor Datatype

**Note:** Tensor datatype is one of the 3 big errors you'll run into with PyTorch & deep learning:

1. Tensors not right datatype

2.Tensor not right shape

In [32]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [33]:
tensor = torch.tensor( [1.0, 2.0, 3.0],dtype=torch.float32)
print(tensor)


tensor([1., 2., 3.])


In [34]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [35]:
float_16_tensor = float_32_tensor

In [36]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [37]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [38]:
#create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3088, 0.0427, 0.1937, 0.9930],
        [0.7967, 0.9717, 0.4674, 0.0707],
        [0.3446, 0.0897, 0.9593, 0.7505]])

In [39]:
#find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3088, 0.0427, 0.1937, 0.9930],
        [0.7967, 0.9717, 0.4674, 0.0707],
        [0.3446, 0.0897, 0.9593, 0.7505]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


###manipulating Tensors ( tensor operation)

Tensor operattion include:

*Addition

*Subtraction

*Multiplication(element-wise)

*division

*Matrix Multiplication

In [40]:
#create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [41]:
#multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [42]:
tensor

tensor([1, 2, 3])

In [43]:
#subtract
tensor - 10

tensor([-9, -8, -7])

In [44]:
#divide
tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [45]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [46]:
torch.add(tensor,10)

tensor([11, 12, 13])

Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1.Element-wise multiplication

2.Matrix multiplication(dot product)

There are two main rules that performing matrix multiplication

1. The **inner dimensions** must match:

 *(3,2) @ (3,2) won't work

 *(2,3) @ (3,2) will work

 *(3,2) @ (2,3) will work


2.The resulting matrix has the shape of the **outer dimension**:

*(2,3) @ (3,2) -> (2,2)

*(3,2) 2 (2,3) -. (3,3)




In [47]:
torch.matmul(torch.rand(10,10),torch.rand(10,10))

tensor([[2.3364, 3.0066, 1.9980, 1.9031, 2.8928, 1.5945, 1.0528, 1.2755, 2.3939,
         1.9556],
        [3.5800, 3.2951, 2.5348, 2.6264, 3.9125, 2.3169, 1.9234, 1.8786, 2.6529,
         2.7673],
        [4.0034, 4.0745, 2.6478, 3.1303, 4.3615, 2.5289, 1.8144, 1.8436, 3.4569,
         3.2753],
        [3.0298, 3.0893, 2.0595, 2.3333, 3.2961, 2.0383, 1.6972, 1.6111, 2.7873,
         2.6720],
        [1.9705, 1.9061, 1.9700, 1.9982, 1.8962, 2.0433, 1.5957, 1.1845, 2.1654,
         2.2158],
        [2.5499, 2.5198, 1.5925, 1.8796, 2.7485, 1.4638, 1.2643, 1.2044, 2.0715,
         2.0531],
        [4.3140, 4.1463, 3.3989, 3.7546, 4.8033, 3.3442, 2.8013, 2.2637, 3.9425,
         3.6089],
        [2.6767, 2.0358, 1.6526, 2.2691, 2.5961, 1.8945, 1.3564, 1.1296, 1.6844,
         2.2228],
        [3.8114, 3.4333, 2.2243, 2.7249, 3.7686, 2.2475, 1.7498, 2.1724, 3.4223,
         2.9098],
        [4.0005, 3.4683, 2.9299, 3.5191, 3.9731, 3.0536, 2.0442, 1.7253, 3.3349,
         3.5152]])

In [48]:
#Elementwise multiplication
print(tensor,"*",tensor)
print(f"Equals:{tensor * tensor}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [49]:
#matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [50]:
#matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [51]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
  print(value)



tensor(1)
tensor(5)
tensor(14)
CPU times: user 722 µs, sys: 0 ns, total: 722 µs
Wall time: 796 µs


In [52]:
tensor @ tensor

tensor(14)

In [53]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 28 µs, sys: 4 µs, total: 32 µs
Wall time: 34.3 µs


tensor(14)

### one of the most common errors in deep learning: shape errors

In [54]:
 #Shape for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])


#torch.mm(tensor_A,tensor_B) #torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A, tensor_B.T)


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [55]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor tensor

In [56]:
tensor_B,tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [57]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [58]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape} , tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying : {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
torch.matmul(tensor_A, tensor_B.T)

Original shapes: tensor_A = torch.Size([3, 2]) , tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying : torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [59]:
print(f"Original shapes : tensor_A = {tensor_A.shape} ,tensor_B = {tensor_B.shape}")
print(f"New shapes:tensorA.T = {tensor_A.shape} (same shape as above), tensor_B = {tensor_B.T.shape}")
print(f"Multiplying : {tensor_A.T.shape} @ {tensor_B.shape} <- inner dimension must match")
print("Output:\n")
out = torch.matmul(tensor_A.T, tensor_B)
print(output)

Original shapes : tensor_A = torch.Size([3, 2]) ,tensor_B = torch.Size([3, 2])
New shapes:tensorA.T = torch.Size([3, 2]) (same shape as above), tensor_B = torch.Size([2, 3])
Multiplying : torch.Size([2, 3]) @ torch.Size([3, 2]) <- inner dimension must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


Finding the min ,max , mean, sum,etc (tensor aggregation)

In [60]:
#create a tensor
x= torch.arange(1,100,10)
x , x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [61]:
# Find the main
torch.min(x) , x.min()

(tensor(1), tensor(1))

In [62]:
#Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)) ,x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [63]:
#find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min max

In [64]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [65]:
# find the position that has the min value with argminn() -> returns index position of the target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [66]:
#find the position in tensor that has the maximum value with argmax
x.argmax()

tensor(9)

In [67]:
x[9]

tensor(91)

# reshaping ,stacking , squeezing and unsquezzing tensore

* Reshaping - reshape an input tensor to a defined shape

* view  - return a view of an input tensor of certain shape but keep the same memory as the original tensor

* stacking - combine muultiple tensors on top of each other (vstack) or side by side (hstack)

* squeeze - remove all dimension from a tensor

* unsqueeze - add a dimension to a target tensor

* permute - return a view of the input with dimension permute(swapped) in a certain way

In [68]:
# lets create a tesor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [69]:
# add a extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [70]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [71]:
#changing z changes x ( because a view of a tensor shares the saame memory as the original input)
z[:,0] =5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [72]:
# stack tensors on top of eachother
x_stacked = torch.stack([x,x,x,x],dim=0 )
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

squeeze

In [73]:
#tourch.squeeze() -- remove  all single dimensions from a target tensor
print(f"previous tensor: {x_reshaped}")
print(f"previous shape: {x_reshaped.shape}")

#remove extra dimension from x_shaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew  tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
previous shape: torch.Size([1, 9])

New  tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [74]:
#tourch.unsqueeze() -- remove  all single dimensions from a target tensor
print(f"previous target: {x_squeezed}")
print(f"previous shape: {x_squeezed.shape}")

#add extra dimension from x_shaped
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew  tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape: torch.Size([9])

New  tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [75]:
#torch.permute - reaarabges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) #[height,width,color_channels]

# permute the original tensor to rearrange the axis (or dim) oredr
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2,2->0

print(f"previous shape: {x_original.shape}")
print(f"new shape: {x_permuted.shape}") #[color_channel,height,width]

previous shape: torch.Size([224, 224, 3])
new shape: torch.Size([3, 224, 224])


In [76]:
x_original[0,0,0] = 728218
x_original[0,0,0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

## Indexing (selecting data from tensors)

Indexing with Pytorch is similar to indexing with numpy

In [77]:
# create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [78]:
# lets a index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [79]:
#lets index in middle bracket
x[0,0]
#x[0][0]

tensor([1, 2, 3])

In [80]:
# Lets index on the most innefr barcket (last dimension)
x[0][1][1]

tensor(5)

In [81]:
# you can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [82]:
# get all values of 0th and 1st dimension but only index 1 of the 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [83]:
# get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [84]:
# get index o of 0th 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [85]:
# index on x to return 9
x[:,2,2]



tensor([9])

In [86]:
# index on x to return 3
x[:,0,2]


tensor([3])

In [87]:
# index on x return 6
x[:,1,2]

tensor([6])

## Pytorch tensor & Numpy

Numpy is a popular scientific python numerical computing library.

and because of this ,pytorch has functionality to  intercat with it.

* Data in Numpy want in Pytorch tensor -> torch.form_numpy(ndarray)

* PyTorch tensor -> Numpy -> torch.Tensor.numpy()

In [88]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
#tensor = torch.from_numpy(array).type(torch.float32)
#warning : when converting from numpy -> pytorch , pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [89]:
array.dtype

dtype('float64')

In [90]:
 #torch.arange(1.0,8.0).dtype

In [91]:
# change the value of array, what will this do to 'tensor'?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [92]:
# tensor to numpy array
tensor= torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [93]:
# change the tensor , what happens to 'numpy_tensor'
tensor = tensor +1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)

In short how a neural network learns:

start with random numbers -> tensor operations -> update random no.s to try and make them representations of the data -> again -> again p> again ...

To reduce the randomness in neural networks and Pytorch comes the concept of random seed

Esentially what the random seed does in the 'flavor' the randomness

In [94]:
import torch
# create two rand tensores
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6552, 0.9098, 0.9226, 0.1298],
        [0.0013, 0.6984, 0.2372, 0.8202],
        [0.5590, 0.6974, 0.8694, 0.5034]])
tensor([[0.8587, 0.6742, 0.8189, 0.6365],
        [0.6516, 0.4773, 0.1283, 0.7966],
        [0.4910, 0.9180, 0.4824, 0.2703]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [100]:
# lets make rand but reproducable tensors
import torch

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)   # first tensor


torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)   # second tensor continues RNG

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and Pytorch objects on the GPUs (and making faster computations)

GPU = faster computation on nos


### 1. Getting a GPU

Easiest - User Google collab fo1 a free GPU

Use your own GPU - investment req

use cloud comuting- GCP, AWS,Azure these services allow you to rent computers on the cloud and access them

In [101]:
! nvidia-smi

Sun Aug 24 16:08:27 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   34C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### 2. check GPU with Pytorch

In [102]:
# check for GPU access with Pytorch
import torch
torch.cuda.is_available()

True

In [103]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

device agnostic code

for pytorch its capable of running computeon the GPU or CPU,its best pratices to setup device agnostic code

In [104]:
# Count number of devices
torch.cuda.device_count()

1