<a href="https://colab.research.google.com/github/shishiradk/pytorch-pratices/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [206]:
!nvidia-smi


/bin/bash: line 1: nvidia-smi: command not found


In [207]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
print(torch.__version__)

2.8.0+cu126


introduction to tensors
creating tensor

In [208]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [209]:
scalar.ndim

0

In [210]:
#get tensor back as python int
scalar.item()

7

In [211]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [212]:
vector.ndim

1

In [213]:
vector.shape

torch.Size([2])

In [214]:
#matrix
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [215]:
MATRIX.ndim

2

In [216]:
MATRIX[1]

tensor([ 9, 10])

In [217]:
MATRIX.shape

torch.Size([2, 2])

In [218]:
#TENSOR
TENSOR = torch.tensor([[[1,2,4],
                         [2,3,4],
                         [4,5,6]]])

In [219]:
TENSOR

tensor([[[1, 2, 4],
         [2, 3, 4],
         [4, 5, 6]]])

In [220]:
TENSOR.ndim

3

In [221]:
TENSOR.shape

torch.Size([1, 3, 3])

In [222]:
TENSOR[0]

tensor([[1, 2, 4],
        [2, 3, 4],
        [4, 5, 6]])

In [223]:
TENSOR = torch.tensor([[[6,7,8],
                        [5,6,7],
                        [4,5,6]]])
TENSOR

tensor([[[6, 7, 8],
         [5, 6, 7],
         [4, 5, 6]]])

In [224]:
TENSOR.ndim

3

In [225]:
TENSOR.shape

torch.Size([1, 3, 3])

In [226]:
TENSOR[0]

tensor([[6, 7, 8],
        [5, 6, 7],
        [4, 5, 6]])

In [227]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(10,10,10)
random_tensor

tensor([[[0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666, 0.6274,
          0.2696, 0.4414],
         [0.2969, 0.8317, 0.1053, 0.2695, 0.3588, 0.1994, 0.5472, 0.0062,
          0.9516, 0.0753],
         [0.8860, 0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423,
          0.6343, 0.3644],
         [0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895, 0.7539, 0.1952,
          0.0050, 0.3068],
         [0.1165, 0.9103, 0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447,
          0.5315, 0.1587],
         [0.6542, 0.3278, 0.6532, 0.3958, 0.9147, 0.2036, 0.2018, 0.2018,
          0.9497, 0.6666],
         [0.9811, 0.0874, 0.0041, 0.1088, 0.1637, 0.7025, 0.6790, 0.9155,
          0.2418, 0.1591],
         [0.7653, 0.2979, 0.8035, 0.3813, 0.7860, 0.1115, 0.2477, 0.6524,
          0.6057, 0.3725],
         [0.7980, 0.8399, 0.1374, 0.2331, 0.9578, 0.3313, 0.3227, 0.0162,
          0.2137, 0.6249],
         [0.4340, 0.1371, 0.5117, 0.1585, 0.0758, 0.2247, 0.0624, 0.1816,
          0.9998,

In [228]:
random_tensor.ndim

3

In [229]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224))#height,width,color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [230]:
torch.rand(3,3)

tensor([[0.5526, 0.6463, 0.8674],
        [0.5501, 0.7107, 0.8877],
        [0.0559, 0.4310, 0.1174]])

In [231]:
#zeros and ones
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [232]:
#create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [233]:
#use torch.range()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [234]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [235]:
one_to_ten.shape

torch.Size([10])

In [236]:
ten_zero = torch.zeros_like(input=one_to_ten)
ten_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor Datatype

**Note:** Tensor datatype is one of the 3 big errors you'll run into with PyTorch & deep learning:

1. Tensors not right datatype

2.Tensor not right shape

In [237]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [238]:
tensor = torch.tensor( [1.0, 2.0, 3.0],dtype=torch.float32)
print(tensor)


tensor([1., 2., 3.])


In [239]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [240]:
float_16_tensor = float_32_tensor

In [241]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [242]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [243]:
#create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6206, 0.6467, 0.4613, 0.0257],
        [0.3717, 0.8746, 0.9029, 0.5850],
        [0.0277, 0.9222, 0.8971, 0.8050]])

In [244]:
#find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.6206, 0.6467, 0.4613, 0.0257],
        [0.3717, 0.8746, 0.9029, 0.5850],
        [0.0277, 0.9222, 0.8971, 0.8050]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


###manipulating Tensors ( tensor operation)

Tensor operattion include:

*Addition

*Subtraction

*Multiplication(element-wise)

*division

*Matrix Multiplication

In [245]:
#create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [246]:
#multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [247]:
tensor

tensor([1, 2, 3])

In [248]:
#subtract
tensor - 10

tensor([-9, -8, -7])

In [249]:
#divide
tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [250]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [251]:
torch.add(tensor,10)

tensor([11, 12, 13])

Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1.Element-wise multiplication

2.Matrix multiplication(dot product)

There are two main rules that performing matrix multiplication

1. The **inner dimensions** must match:

 *(3,2) @ (3,2) won't work

 *(2,3) @ (3,2) will work

 *(3,2) @ (2,3) will work


2.The resulting matrix has the shape of the **outer dimension**:

*(2,3) @ (3,2) -> (2,2)

*(3,2) 2 (2,3) -. (3,3)




In [252]:
torch.matmul(torch.rand(10,10),torch.rand(10,10))

tensor([[2.7117, 2.0622, 2.5863, 2.1457, 2.0896, 1.6061, 1.7825, 1.8751, 2.3502,
         1.7002],
        [3.0178, 2.6138, 2.8346, 2.4094, 2.4324, 2.1907, 2.0274, 2.4441, 2.2593,
         1.3435],
        [3.4973, 2.6384, 3.1233, 2.6020, 2.5263, 2.6218, 2.3145, 3.0057, 2.7152,
         1.8897],
        [3.1766, 3.0941, 3.3008, 2.6062, 3.0351, 2.5987, 2.3485, 3.4902, 2.8157,
         2.3648],
        [2.2801, 2.4105, 2.9020, 1.7084, 1.9103, 2.0863, 1.7321, 2.0148, 1.3191,
         0.8829],
        [2.5115, 1.9726, 2.0527, 1.6507, 1.9636, 1.8397, 1.8290, 2.5528, 1.9637,
         1.8608],
        [2.2870, 1.9241, 2.5085, 1.7992, 2.1008, 1.5782, 1.4354, 1.6055, 1.8675,
         1.9333],
        [3.3784, 2.9829, 3.0129, 2.5665, 2.9234, 2.7184, 2.0413, 2.7473, 2.1254,
         1.9573],
        [3.4252, 2.3626, 2.8720, 2.2046, 2.5970, 2.1652, 2.4785, 2.8804, 2.8544,
         1.9345],
        [3.7009, 2.9906, 3.3055, 2.2970, 2.9922, 2.3458, 2.6162, 2.8795, 2.5558,
         2.2717]])

In [253]:
#Elementwise multiplication
print(tensor,"*",tensor)
print(f"Equals:{tensor * tensor}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [254]:
#matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [255]:
#matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [256]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
  print(value)



tensor(1)
tensor(5)
tensor(14)
CPU times: user 1.59 ms, sys: 59 µs, total: 1.65 ms
Wall time: 2.55 ms


In [257]:
tensor @ tensor

tensor(14)

In [258]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 79 µs, sys: 0 ns, total: 79 µs
Wall time: 82.5 µs


tensor(14)

### one of the most common errors in deep learning: shape errors

In [259]:
 #Shape for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])


#torch.mm(tensor_A,tensor_B) #torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A, tensor_B.T)


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [260]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor tensor

In [261]:
tensor_B,tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [262]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [263]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape} , tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying : {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
torch.matmul(tensor_A, tensor_B.T)

Original shapes: tensor_A = torch.Size([3, 2]) , tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying : torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [264]:
print(f"Original shapes : tensor_A = {tensor_A.shape} ,tensor_B = {tensor_B.shape}")
print(f"New shapes:tensorA.T = {tensor_A.shape} (same shape as above), tensor_B = {tensor_B.T.shape}")
print(f"Multiplying : {tensor_A.T.shape} @ {tensor_B.shape} <- inner dimension must match")
print("Output:\n")
out = torch.matmul(tensor_A.T, tensor_B)
print(output)

Original shapes : tensor_A = torch.Size([3, 2]) ,tensor_B = torch.Size([3, 2])
New shapes:tensorA.T = torch.Size([3, 2]) (same shape as above), tensor_B = torch.Size([2, 3])
Multiplying : torch.Size([2, 3]) @ torch.Size([3, 2]) <- inner dimension must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


Finding the min ,max , mean, sum,etc (tensor aggregation)

In [265]:
#create a tensor
x= torch.arange(1,100,10)
x , x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [266]:
# Find the main
torch.min(x) , x.min()

(tensor(1), tensor(1))

In [267]:
#Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)) ,x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [268]:
#find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min max

In [269]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [270]:
# find the position that has the min value with argminn() -> returns index position of the target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [271]:
#find the position in tensor that has the maximum value with argmax
x.argmax()

tensor(9)

In [272]:
x[9]

tensor(91)

# reshaping ,stacking , squeezing and unsquezzing tensore

* Reshaping - reshape an input tensor to a defined shape

* view  - return a view of an input tensor of certain shape but keep the same memory as the original tensor

* stacking - combine muultiple tensors on top of each other (vstack) or side by side (hstack)

* squeeze - remove all dimension from a tensor

* unsqueeze - add a dimension to a target tensor

* permute - return a view of the input with dimension permute(swapped) in a certain way

In [273]:
# lets create a tesor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [274]:
# add a extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [275]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [276]:
#changing z changes x ( because a view of a tensor shares the saame memory as the original input)
z[:,0] =5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [277]:
# stack tensors on top of eachother
x_stacked = torch.stack([x,x,x,x],dim=0 )
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

squeeze

In [278]:
#tourch.squeeze() -- remove  all single dimensions from a target tensor
print(f"previous tensor: {x_reshaped}")
print(f"previous shape: {x_reshaped.shape}")

#remove extra dimension from x_shaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew  tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
previous shape: torch.Size([1, 9])

New  tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [279]:
#tourch.unsqueeze() -- remove  all single dimensions from a target tensor
print(f"previous target: {x_squeezed}")
print(f"previous shape: {x_squeezed.shape}")

#add extra dimension from x_shaped
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew  tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape: torch.Size([9])

New  tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [280]:
#torch.permute - reaarabges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) #[height,width,color_channels]

# permute the original tensor to rearrange the axis (or dim) oredr
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2,2->0

print(f"previous shape: {x_original.shape}")
print(f"new shape: {x_permuted.shape}") #[color_channel,height,width]

previous shape: torch.Size([224, 224, 3])
new shape: torch.Size([3, 224, 224])


In [281]:
x_original[0,0,0] = 728218
x_original[0,0,0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

## Indexing (selecting data from tensors)

Indexing with Pytorch is similar to indexing with numpy

In [282]:
# create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [283]:
# lets a index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [284]:
#lets index in middle bracket
x[0,0]
#x[0][0]

tensor([1, 2, 3])

In [285]:
# Lets index on the most innefr barcket (last dimension)
x[0][1][1]

tensor(5)

In [286]:
# you can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [287]:
# get all values of 0th and 1st dimension but only index 1 of the 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [288]:
# get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [289]:
# get index o of 0th 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [290]:
# index on x to return 9
x[:,2,2]



tensor([9])

In [291]:
# index on x to return 3
x[:,0,2]


tensor([3])

In [292]:
# index on x return 6
x[:,1,2]

tensor([6])

## Pytorch tensor & Numpy

Numpy is a popular scientific python numerical computing library.

and because of this ,pytorch has functionality to  intercat with it.

* Data in Numpy want in Pytorch tensor -> torch.form_numpy(ndarray)

* PyTorch tensor -> Numpy -> torch.Tensor.numpy()

In [293]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
#tensor = torch.from_numpy(array).type(torch.float32)
#warning : when converting from numpy -> pytorch , pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [294]:
array.dtype

dtype('float64')

In [295]:
 #torch.arange(1.0,8.0).dtype

In [296]:
# change the value of array, what will this do to 'tensor'?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [297]:
# tensor to numpy array
tensor= torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [298]:
# change the tensor , what happens to 'numpy_tensor'
tensor = tensor +1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)

In short how a neural network learns:

start with random numbers -> tensor operations -> update random no.s to try and make them representations of the data -> again -> again p> again ...

To reduce the randomness in neural networks and Pytorch comes the concept of random seed

Esentially what the random seed does in the 'flavor' the randomness

In [299]:
import torch
# create two rand tensores
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2260, 0.9020, 0.6826, 0.5829],
        [0.6185, 0.1276, 0.3567, 0.1097],
        [0.4120, 0.1982, 0.0454, 0.8953]])
tensor([[0.4765, 0.9446, 0.1468, 0.8342],
        [0.5079, 0.1318, 0.4189, 0.5794],
        [0.0088, 0.8161, 0.0113, 0.7179]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [300]:
# lets make rand but reproducable tensors
import torch

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)   # first tensor


torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)   # second tensor continues RNG

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and Pytorch objects on the GPUs (and making faster computations)

GPU = faster computation on nos


### 1. Getting a GPU

Easiest - User Google collab fo1 a free GPU

Use your own GPU - investment req

use cloud comuting- GCP, AWS,Azure these services allow you to rent computers on the cloud and access them

In [301]:
! nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


### 2. check GPU with Pytorch

In [302]:
# check for GPU access with Pytorch
import torch
torch.cuda.is_available()

False

In [303]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

device agnostic code

for pytorch its capable of running computeon the GPU or CPU,its best pratices to setup device agnostic code

In [304]:
# Count number of devices
torch.cuda.device_count()

0

## 3. putting tensors (and models) on the GPU

In [305]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [306]:
# move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

### 4. Moving tensor back to cpu

In [307]:
# if tensor in GPU , cant transform it to numpy
# tensor_on_gpu.numpy()


In [308]:
# to fix the GPU tensor with numpy issue ,we can first set it to the cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])