<a href="https://colab.research.google.com/github/shishiradk/pytorch-pratices/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi


Fri Mar 21 17:44:16 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   44C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
print(torch.__version__)

2.6.0+cu124


introduction to tensors
creating tensor

In [3]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#get tensor back as python int
scalar.item()

7

In [6]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#matrix
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
#TENSOR
TENSOR = torch.tensor([[[1,2,4],
                         [2,3,4],
                         [4,5,6]]])

In [14]:
TENSOR

tensor([[[1, 2, 4],
         [2, 3, 4],
         [4, 5, 6]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 4],
        [2, 3, 4],
        [4, 5, 6]])

In [18]:
TENSOR = torch.tensor([[[6,7,8],
                        [5,6,7],
                        [4,5,6]]])
TENSOR

tensor([[[6, 7, 8],
         [5, 6, 7],
         [4, 5, 6]]])

In [19]:
TENSOR.ndim

3

In [20]:
TENSOR.shape

torch.Size([1, 3, 3])

In [21]:
TENSOR[0]

tensor([[6, 7, 8],
        [5, 6, 7],
        [4, 5, 6]])

In [22]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(10,10,10)
random_tensor

tensor([[[6.3162e-01, 4.9528e-01, 3.6608e-01, 2.9302e-01, 1.1218e-01,
          6.2653e-01, 6.3704e-01, 8.6953e-01, 9.8138e-01, 3.6672e-01],
         [1.6448e-01, 3.3448e-01, 9.6688e-01, 5.4930e-01, 1.9095e-02,
          5.4988e-01, 5.5195e-01, 2.1451e-01, 1.0242e-01, 6.7545e-01],
         [7.3032e-01, 7.4938e-01, 8.4487e-01, 5.0455e-02, 7.1548e-01,
          1.7677e-01, 6.6339e-01, 9.9510e-01, 9.2433e-01, 7.6185e-01],
         [7.3651e-01, 2.2238e-01, 1.2684e-01, 6.8286e-01, 4.6809e-01,
          9.0194e-01, 2.2123e-01, 9.2637e-02, 1.4750e-01, 1.3863e-01],
         [7.9960e-01, 5.8072e-01, 1.3926e-01, 8.7651e-03, 6.3588e-01,
          6.3293e-02, 6.8098e-01, 8.5847e-01, 6.6818e-01, 3.0912e-01],
         [2.1621e-01, 3.4685e-01, 6.5830e-01, 2.8540e-01, 8.0132e-01,
          3.9535e-01, 4.0124e-01, 7.0475e-01, 8.5865e-01, 8.9154e-01],
         [3.5510e-01, 1.3768e-01, 9.4570e-01, 4.0374e-01, 6.3286e-01,
          5.3093e-01, 9.7422e-02, 5.5388e-02, 2.0245e-01, 5.8940e-01],
         [2.2

In [23]:
random_tensor.ndim

3

In [24]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224))#height,width,color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [25]:
torch.rand(3,3)

tensor([[0.3710, 0.5277, 0.9142],
        [0.9162, 0.0754, 0.3269],
        [0.8275, 0.1406, 0.6265]])

In [26]:
#zeros and ones
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
#create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
#use torch.range()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
one_to_ten.shape

torch.Size([10])

In [31]:
ten_zero = torch.zeros_like(input=one_to_ten)
ten_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor Datatype

**Note:** Tensor datatype is one of the 3 big errors you'll run into with PyTorch & deep learning:

1. Tensors not right datatype

2.Tensor not right shape

In [32]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [33]:
tensor = torch.tensor( [1.0, 2.0, 3.0],dtype=torch.float32)
print(tensor)


tensor([1., 2., 3.])


In [34]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [35]:
float_16_tensor = float_32_tensor

In [36]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [37]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [38]:
#create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4605, 0.4862, 0.8249, 0.3545],
        [0.5869, 0.3897, 0.9503, 0.1838],
        [0.8402, 0.1539, 0.5910, 0.1477]])

In [39]:
#find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4605, 0.4862, 0.8249, 0.3545],
        [0.5869, 0.3897, 0.9503, 0.1838],
        [0.8402, 0.1539, 0.5910, 0.1477]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


###manipulating Tensors ( tensor operation)

Tensor operattion include:

*Addition

*Subtraction

*Multiplication(element-wise)

*division

*Matrix Multiplication

In [40]:
#create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [41]:
#multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [42]:
tensor

tensor([1, 2, 3])

In [43]:
#subtract
tensor - 10

tensor([-9, -8, -7])

In [44]:
#divide
tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [45]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [46]:
torch.add(tensor,10)

tensor([11, 12, 13])

Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1.Element-wise multiplication

2.Matrix multiplication(dot product)

There are two main rules that performing matrix multiplication

1. The **inner dimensions** must match:

 *(3,2) @ (3,2) won't work

 *(2,3) @ (3,2) will work

 *(3,2) @ (2,3) will work


2.The resulting matrix has the shape of the **outer dimension**:

*(2,3) @ (3,2) -> (2,2)

*(3,2) 2 (2,3) -. (3,3)




In [47]:
torch.matmul(torch.rand(10,10),torch.rand(10,10))

tensor([[2.9457, 3.0755, 3.1885, 2.5933, 3.3562, 2.2052, 2.3206, 2.2960, 3.2972,
         3.5724],
        [2.1302, 2.0070, 2.5234, 1.5101, 2.1775, 1.4176, 1.7805, 2.0573, 2.3989,
         2.5558],
        [2.3986, 2.2689, 2.2739, 1.3948, 2.2069, 1.4521, 1.6470, 2.2737, 2.0436,
         2.6106],
        [3.3437, 3.2652, 2.9273, 2.5534, 3.6636, 2.3439, 2.0450, 3.1008, 3.2236,
         3.7433],
        [3.1257, 2.9357, 3.0689, 3.0485, 3.6264, 2.7022, 2.0065, 2.6568, 3.4772,
         3.7054],
        [2.6118, 2.3687, 2.6845, 1.9875, 2.8235, 1.7263, 1.4386, 2.3199, 2.9801,
         2.7914],
        [3.0424, 3.0458, 3.1456, 2.1556, 3.0915, 2.0271, 2.1171, 2.6081, 3.0137,
         3.3062],
        [2.7550, 2.9251, 3.1899, 2.4686, 3.1250, 2.2029, 1.8593, 2.8151, 2.5966,
         2.8669],
        [3.1751, 3.4529, 3.7341, 3.1564, 3.5218, 2.7253, 2.5273, 2.6690, 3.1678,
         3.7611],
        [2.6365, 2.2762, 2.3625, 1.8718, 2.6170, 1.7667, 1.4552, 2.6052, 2.9764,
         3.0605]])

In [48]:
#Elementwise multiplication
print(tensor,"*",tensor)
print(f"Equals:{tensor * tensor}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [49]:
#matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [50]:
#matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [51]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
  print(value)



tensor(1)
tensor(5)
tensor(14)
CPU times: user 1.25 ms, sys: 46 µs, total: 1.29 ms
Wall time: 1.37 ms


In [52]:
tensor @ tensor

tensor(14)

In [53]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 93 µs, sys: 16 µs, total: 109 µs
Wall time: 125 µs


tensor(14)

### one of the most common errors in deep learning: shape errors

In [54]:
 #Shape for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])


#torch.mm(tensor_A,tensor_B) #torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A, tensor_B.T)


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [55]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor tensor

In [56]:
tensor_B,tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [57]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

aaba