<a href="https://colab.research.google.com/github/shishiradk/pytorch-pratices/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!nvidia-smi


Sat Mar  8 07:14:31 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   47C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
print(torch.__version__)

2.5.1+cu124


introduction to tensors
creating tensor

In [4]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [5]:
scalar.ndim

0

In [6]:
#get tensor back as python int
scalar.item()

7

In [7]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#matrix
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
#TENSOR
TENSOR = torch.tensor([[[1,2,4],
                         [2,3,4],
                         [4,5,6]]])

In [15]:
TENSOR

tensor([[[1, 2, 4],
         [2, 3, 4],
         [4, 5, 6]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 4],
        [2, 3, 4],
        [4, 5, 6]])

In [19]:
TENSOR = torch.tensor([[[6,7,8],
                        [5,6,7],
                        [4,5,6]]])
TENSOR

tensor([[[6, 7, 8],
         [5, 6, 7],
         [4, 5, 6]]])

In [20]:
TENSOR.ndim

3

In [21]:
TENSOR.shape

torch.Size([1, 3, 3])

In [22]:
TENSOR[0]

tensor([[6, 7, 8],
        [5, 6, 7],
        [4, 5, 6]])

In [23]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(10,10,10)
random_tensor

tensor([[[0.3370, 0.7600, 0.2792, 0.9081, 0.0522, 0.0245, 0.3914, 0.5066,
          0.7308, 0.2967],
         [0.6687, 0.5039, 0.2939, 0.5409, 0.0275, 0.0615, 0.0472, 0.8147,
          0.8043, 0.8135],
         [0.8542, 0.6446, 0.6135, 0.6707, 0.3892, 0.8496, 0.0911, 0.9563,
          0.0211, 0.4423],
         [0.8938, 0.0538, 0.2690, 0.4919, 0.4933, 0.5879, 0.3374, 0.7893,
          0.2986, 0.3308],
         [0.7462, 0.2572, 0.7426, 0.5952, 0.4130, 0.3130, 0.0802, 0.0499,
          0.1747, 0.4030],
         [0.6322, 0.3224, 0.6212, 0.0691, 0.2253, 0.3566, 0.1806, 0.7505,
          0.6745, 0.6805],
         [0.8239, 0.8753, 0.1310, 0.8521, 0.6515, 0.7606, 0.0999, 0.4796,
          0.0683, 0.8222],
         [0.8751, 0.1757, 0.4550, 0.1096, 0.4501, 0.6786, 0.4091, 0.8974,
          0.7571, 0.8096],
         [0.6615, 0.5323, 0.8216, 0.2551, 0.9771, 0.2166, 0.3295, 0.4107,
          0.9396, 0.9083],
         [0.1047, 0.8083, 0.8805, 0.3062, 0.1953, 0.9181, 0.4488, 0.8499,
          0.9865,

In [24]:
random_tensor.ndim

3

In [25]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224))#height,width,color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [26]:
torch.rand(3,3)

tensor([[0.1791, 0.2634, 0.1611],
        [0.2643, 0.3949, 0.7721],
        [0.1823, 0.2467, 0.9315]])

In [27]:
#zeros and ones
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
#create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [29]:
#use torch.range()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
one_to_ten.shape

torch.Size([10])

In [32]:
ten_zero = torch.zeros_like(input=one_to_ten)
ten_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor Datatype

In [34]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])