<a href="https://colab.research.google.com/github/shishiradk/pytorch-pratices/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi


Sun Mar  9 08:01:24 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   58C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
print(torch.__version__)

2.5.1+cu124


introduction to tensors
creating tensor

In [3]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#get tensor back as python int
scalar.item()

7

In [6]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#matrix
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
#TENSOR
TENSOR = torch.tensor([[[1,2,4],
                         [2,3,4],
                         [4,5,6]]])

In [14]:
TENSOR

tensor([[[1, 2, 4],
         [2, 3, 4],
         [4, 5, 6]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 4],
        [2, 3, 4],
        [4, 5, 6]])

In [18]:
TENSOR = torch.tensor([[[6,7,8],
                        [5,6,7],
                        [4,5,6]]])
TENSOR

tensor([[[6, 7, 8],
         [5, 6, 7],
         [4, 5, 6]]])

In [19]:
TENSOR.ndim

3

In [20]:
TENSOR.shape

torch.Size([1, 3, 3])

In [21]:
TENSOR[0]

tensor([[6, 7, 8],
        [5, 6, 7],
        [4, 5, 6]])

In [22]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(10,10,10)
random_tensor

tensor([[[0.4385, 0.0476, 0.4628, 0.4541, 0.8916, 0.9794, 0.4721, 0.0948,
          0.6383, 0.8093],
         [0.2655, 0.3720, 0.9811, 0.1915, 0.2407, 0.8698, 0.5543, 0.2090,
          0.3000, 0.8808],
         [0.3032, 0.3420, 0.3766, 0.6466, 0.8244, 0.8532, 0.5184, 0.8867,
          0.6190, 0.5944],
         [0.4002, 0.3237, 0.6510, 0.4260, 0.9073, 0.7793, 0.3820, 0.5017,
          0.9319, 0.7819],
         [0.2908, 0.5182, 0.3318, 0.0822, 0.6364, 0.8568, 0.9371, 0.0589,
          0.9450, 0.3443],
         [0.9888, 0.9479, 0.6341, 0.2763, 0.1731, 0.9575, 0.4893, 0.5381,
          0.2869, 0.8554],
         [0.9749, 0.4842, 0.1050, 0.7489, 0.0421, 0.6852, 0.6916, 0.6309,
          0.5259, 0.2450],
         [0.9115, 0.3476, 0.5893, 0.6102, 0.0886, 0.6944, 0.3376, 0.3416,
          0.4456, 0.2759],
         [0.2146, 0.6154, 0.1302, 0.8632, 0.5943, 0.8786, 0.4319, 0.9528,
          0.0645, 0.5421],
         [0.4686, 0.2691, 0.6935, 0.4362, 0.9582, 0.5138, 0.2655, 0.7963,
          0.9702,

In [23]:
random_tensor.ndim

3

In [24]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224))#height,width,color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [25]:
torch.rand(3,3)

tensor([[0.7130, 0.0458, 0.3744],
        [0.6605, 0.5968, 0.1474],
        [0.3199, 0.9975, 0.5423]])

In [26]:
#zeros and ones
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
#create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
#use torch.range()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
one_to_ten.shape

torch.Size([10])

In [31]:
ten_zero = torch.zeros_like(input=one_to_ten)
ten_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor Datatype

**Note:** Tensor datatype is one of the 3 big errors you'll run into with PyTorch & deep learning:

1. Tensors not right datatype

2.Tensor not right shape

In [32]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [33]:
tensor = torch.tensor( [1.0, 2.0, 3.0],dtype=torch.float32)
print(tensor)


tensor([1., 2., 3.])


In [34]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [35]:
float_16_tensor = float_32_tensor

In [36]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [37]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [38]:
#create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4702, 0.8670, 0.0875, 0.2174],
        [0.2478, 0.3346, 0.8402, 0.7249],
        [0.8263, 0.6474, 0.5180, 0.6691]])

In [39]:
#find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4702, 0.8670, 0.0875, 0.2174],
        [0.2478, 0.3346, 0.8402, 0.7249],
        [0.8263, 0.6474, 0.5180, 0.6691]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


###manipulating Tensors ( tensor operation)

Tensor operattion include:

*Addition

*Subtraction

*Multiplication(element-wise)

*division

*Matrix Multiplication

In [40]:
#create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [41]:
#multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [42]:
tensor

tensor([1, 2, 3])

In [43]:
#subtract
tensor - 10

tensor([-9, -8, -7])

In [44]:
#divide
tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [45]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [46]:
torch.add(tensor,10)

tensor([11, 12, 13])

Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1.Element-wise multiplication

2.Matrix multiplication(dot product)

There are two main rules that performing matrix multiplication

1. The **inner dimensions** must match:

 *(3,2) @ (3,2) won't work

 *(2,3) @ (3,2) will work

 *(3,2) @ (2,3) will work


2.The resulting matrix has the shape of the **outer dimension**:

*(2,3) @ (3,2) -> (2,2)

*(3,2) 2 (2,3) -. (3,3)




In [47]:
torch.matmul(torch.rand(10,10),torch.rand(10,10))

tensor([[3.5068, 2.7284, 2.6800, 2.8900, 1.7730, 2.8895, 1.8123, 2.3243, 3.3925,
         2.3846],
        [3.9753, 3.1727, 3.6944, 2.6370, 2.6409, 2.4890, 3.0180, 3.1480, 3.3680,
         2.5556],
        [2.4227, 1.7819, 1.9868, 2.1461, 1.8479, 2.1084, 1.5868, 2.4559, 2.5330,
         1.8871],
        [4.0679, 3.3723, 3.1829, 3.7680, 2.4176, 3.4378, 3.0212, 3.2790, 3.7938,
         3.0330],
        [4.1250, 3.5350, 3.2588, 2.6448, 2.1805, 2.8809, 2.9406, 3.3694, 3.8970,
         2.9490],
        [2.2650, 1.8027, 1.7307, 1.9250, 1.9161, 1.3248, 1.5769, 2.0405, 2.0955,
         1.6695],
        [2.7306, 2.0607, 2.5819, 2.4908, 2.3184, 1.7813, 1.7340, 2.3961, 2.4320,
         1.7506],
        [2.3991, 2.1345, 2.1822, 1.8859, 2.1072, 1.8394, 1.4141, 2.3809, 2.4397,
         1.4326],
        [2.9878, 2.1075, 1.8369, 2.0741, 1.5525, 1.9425, 2.1026, 2.1749, 2.7218,
         1.9017],
        [1.8135, 1.2105, 1.2388, 1.0259, 0.9750, 0.8517, 1.1385, 0.9162, 1.3426,
         0.9459]])

In [48]:
#Elementwise multiplication
print(tensor,"*",tensor)
print(f"Equals:{tensor * tensor}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [49]:
#matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [50]:
#matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [51]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
  print(value)



tensor(1)
tensor(5)
tensor(14)
CPU times: user 1.28 ms, sys: 0 ns, total: 1.28 ms
Wall time: 3.05 ms


In [52]:
tensor @ tensor

tensor(14)

In [53]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 39 µs, sys: 7 µs, total: 46 µs
Wall time: 49.8 µs


tensor(14)

### one of the most common errors in deep learning: shape errors

In [60]:
 #Shape for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])


#torch.mm(tensor_A,tensor_B) #torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A, tensor_B.T)


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [61]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor tensor

In [62]:
tensor_B,tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [65]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))