<a href="https://colab.research.google.com/github/shishiradk/pytorch-pratices/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi


/bin/bash: line 1: nvidia-smi: command not found


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
print(torch.__version__)

2.8.0+cu126


introduction to tensors
creating tensor

In [3]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#get tensor back as python int
scalar.item()

7

In [6]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#matrix
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
#TENSOR
TENSOR = torch.tensor([[[1,2,4],
                         [2,3,4],
                         [4,5,6]]])

In [14]:
TENSOR

tensor([[[1, 2, 4],
         [2, 3, 4],
         [4, 5, 6]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 4],
        [2, 3, 4],
        [4, 5, 6]])

In [18]:
TENSOR = torch.tensor([[[6,7,8],
                        [5,6,7],
                        [4,5,6]]])
TENSOR

tensor([[[6, 7, 8],
         [5, 6, 7],
         [4, 5, 6]]])

In [19]:
TENSOR.ndim

3

In [20]:
TENSOR.shape

torch.Size([1, 3, 3])

In [21]:
TENSOR[0]

tensor([[6, 7, 8],
        [5, 6, 7],
        [4, 5, 6]])

In [22]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(10,10,10)
random_tensor

tensor([[[4.7011e-01, 5.3593e-01, 9.3039e-01, 7.2686e-01, 4.0752e-01,
          6.5142e-01, 9.5931e-01, 3.2450e-01, 1.4385e-02, 4.3156e-01],
         [9.7054e-01, 1.8735e-01, 3.5871e-01, 4.4309e-02, 4.0323e-02,
          2.3135e-02, 6.5444e-01, 5.8188e-02, 7.2437e-01, 1.9983e-02],
         [2.5120e-01, 7.7458e-01, 9.4429e-01, 8.9097e-01, 3.0619e-04,
          1.2602e-01, 5.0874e-01, 6.0174e-01, 2.7260e-01, 6.6434e-01],
         [1.1878e-01, 5.2984e-01, 4.5872e-01, 9.8955e-01, 6.4302e-01,
          2.2113e-02, 1.4452e-01, 2.6476e-01, 7.2617e-01, 2.3201e-01],
         [1.1396e-01, 5.4717e-01, 3.8308e-01, 9.3495e-01, 3.5039e-01,
          4.8131e-01, 6.8451e-01, 6.4101e-01, 7.6974e-01, 8.3972e-01],
         [5.2951e-01, 2.0053e-01, 2.5073e-01, 9.6713e-01, 9.6580e-01,
          4.2858e-02, 3.9810e-02, 4.3698e-01, 3.4154e-02, 8.6281e-01],
         [3.1258e-01, 6.0273e-01, 5.4388e-01, 9.3740e-01, 6.2055e-01,
          8.1643e-01, 6.9511e-01, 5.2517e-01, 3.9427e-01, 4.5171e-01],
         [9.8

In [23]:
random_tensor.ndim

3

In [24]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224))#height,width,color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [25]:
torch.rand(3,3)

tensor([[0.4751, 0.8431, 0.5373],
        [0.2824, 0.9117, 0.1372],
        [0.3561, 0.0734, 0.2897]])

In [26]:
#zeros and ones
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
#create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
#use torch.range()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
one_to_ten.shape

torch.Size([10])

In [31]:
ten_zero = torch.zeros_like(input=one_to_ten)
ten_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor Datatype

**Note:** Tensor datatype is one of the 3 big errors you'll run into with PyTorch & deep learning:

1. Tensors not right datatype

2.Tensor not right shape

In [32]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [33]:
tensor = torch.tensor( [1.0, 2.0, 3.0],dtype=torch.float32)
print(tensor)


tensor([1., 2., 3.])


In [34]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [35]:
float_16_tensor = float_32_tensor

In [36]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [37]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [38]:
#create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8648, 0.3368, 0.5101, 0.7034],
        [0.6177, 0.2075, 0.1423, 0.4281],
        [0.1709, 0.8483, 0.7124, 0.7042]])

In [39]:
#find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.8648, 0.3368, 0.5101, 0.7034],
        [0.6177, 0.2075, 0.1423, 0.4281],
        [0.1709, 0.8483, 0.7124, 0.7042]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


###manipulating Tensors ( tensor operation)

Tensor operattion include:

*Addition

*Subtraction

*Multiplication(element-wise)

*division

*Matrix Multiplication

In [40]:
#create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [41]:
#multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [42]:
tensor

tensor([1, 2, 3])

In [43]:
#subtract
tensor - 10

tensor([-9, -8, -7])

In [44]:
#divide
tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [45]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [46]:
torch.add(tensor,10)

tensor([11, 12, 13])

Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1.Element-wise multiplication

2.Matrix multiplication(dot product)

There are two main rules that performing matrix multiplication

1. The **inner dimensions** must match:

 *(3,2) @ (3,2) won't work

 *(2,3) @ (3,2) will work

 *(3,2) @ (2,3) will work


2.The resulting matrix has the shape of the **outer dimension**:

*(2,3) @ (3,2) -> (2,2)

*(3,2) 2 (2,3) -. (3,3)




In [47]:
torch.matmul(torch.rand(10,10),torch.rand(10,10))

tensor([[2.7305, 2.7752, 2.7182, 3.3321, 2.5909, 3.2492, 2.9498, 2.9445, 3.6469,
         1.9705],
        [2.1252, 2.6268, 2.0143, 3.2114, 2.4930, 2.8057, 2.8126, 2.8713, 3.3100,
         1.9055],
        [2.1352, 2.3502, 2.6157, 3.2815, 2.6022, 3.2000, 2.3430, 2.7324, 2.8084,
         2.1385],
        [1.8291, 2.2447, 2.3698, 3.1879, 2.3638, 2.8682, 2.2682, 2.7395, 2.8648,
         1.8275],
        [2.3815, 2.4919, 2.5359, 2.9062, 2.5284, 3.0174, 2.0557, 2.4696, 3.3482,
         1.8935],
        [2.9890, 3.2011, 3.4077, 3.4389, 3.1040, 3.6873, 2.7643, 2.8022, 3.8837,
         2.4472],
        [2.5956, 2.7911, 2.7511, 3.1275, 3.0044, 3.2239, 2.1192, 2.7209, 3.7925,
         2.1022],
        [3.0194, 3.3482, 3.7053, 3.3697, 2.9693, 4.1001, 2.7974, 3.0541, 3.9413,
         2.2306],
        [1.9373, 2.5840, 2.8633, 3.1145, 2.5777, 3.1374, 2.5266, 3.2175, 2.6147,
         1.6040],
        [1.8230, 2.0353, 2.3609, 2.7135, 1.9830, 2.4955, 2.0360, 2.0873, 2.5305,
         1.6338]])

In [48]:
#Elementwise multiplication
print(tensor,"*",tensor)
print(f"Equals:{tensor * tensor}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [49]:
#matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [50]:
#matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [51]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
  print(value)



tensor(1)
tensor(5)
tensor(14)
CPU times: user 1.66 ms, sys: 0 ns, total: 1.66 ms
Wall time: 1.71 ms


In [52]:
tensor @ tensor

tensor(14)

In [53]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 64 µs, sys: 12 µs, total: 76 µs
Wall time: 79.4 µs


tensor(14)

### one of the most common errors in deep learning: shape errors

In [54]:
 #Shape for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])


#torch.mm(tensor_A,tensor_B) #torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A, tensor_B.T)


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [55]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor tensor

In [56]:
tensor_B,tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [57]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [58]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape} , tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying : {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
torch.matmul(tensor_A, tensor_B.T)

Original shapes: tensor_A = torch.Size([3, 2]) , tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying : torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [59]:
print(f"Original shapes : tensor_A = {tensor_A.shape} ,tensor_B = {tensor_B.shape}")
print(f"New shapes:tensorA.T = {tensor_A.shape} (same shape as above), tensor_B = {tensor_B.T.shape}")
print(f"Multiplying : {tensor_A.T.shape} @ {tensor_B.shape} <- inner dimension must match")
print("Output:\n")
out = torch.matmul(tensor_A.T, tensor_B)
print(output)

Original shapes : tensor_A = torch.Size([3, 2]) ,tensor_B = torch.Size([3, 2])
New shapes:tensorA.T = torch.Size([3, 2]) (same shape as above), tensor_B = torch.Size([2, 3])
Multiplying : torch.Size([2, 3]) @ torch.Size([3, 2]) <- inner dimension must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


Finding the min ,max , mean, sum,etc (tensor aggregation)

In [60]:
#create a tensor
x= torch.arange(1,100,10)
x , x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [61]:
# Find the main
torch.min(x) , x.min()

(tensor(1), tensor(1))

In [62]:
#Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)) ,x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [63]:
#find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min max

In [64]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [65]:
# find the position that has the min value with argminn() -> returns index position of the target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [66]:
#find the position in tensor that has the maximum value with argmax
x.argmax()

tensor(9)

In [67]:
x[9]

tensor(91)

# reshaping ,stacking , squeezing and unsquezzing tensore

* Reshaping - reshape an input tensor to a defined shape

* view  - return a view of an input tensor of certain shape but keep the same memory as the original tensor

* stacking - combine muultiple tensors on top of each other (vstack) or side by side (hstack)

* squeeze - remove all dimension from a tensor

* unsqueeze - add a dimension to a target tensor

* permute - return a view of the input with dimension permute(swapped) in a certain way

In [68]:
# lets create a tesor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [69]:
# add a extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [70]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [71]:
#changing z changes x ( because a view of a tensor shares the saame memory as the original input)
z[:,0] =5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [72]:
# stack tensors on top of eachother
x_stacked = torch.stack([x,x,x,x],dim=0 )
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

squeeze

In [73]:
#tourch.squeeze() -- remove  all single dimensions from a target tensor
print(f"previous tensor: {x_reshaped}")
print(f"previous shape: {x_reshaped.shape}")

#remove extra dimension from x_shaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew  tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
previous shape: torch.Size([1, 9])

New  tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [74]:
#tourch.unsqueeze() -- remove  all single dimensions from a target tensor
print(f"previous target: {x_squeezed}")
print(f"previous shape: {x_squeezed.shape}")

#add extra dimension from x_shaped
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew  tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape: torch.Size([9])

New  tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [75]:
#torch.permute - reaarabges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) #[height,width,color_channels]

# permute the original tensor to rearrange the axis (or dim) oredr
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2,2->0

print(f"previous shape: {x_original.shape}")
print(f"new shape: {x_permuted.shape}") #[color_channel,height,width]

previous shape: torch.Size([224, 224, 3])
new shape: torch.Size([3, 224, 224])


In [76]:
x_original[0,0,0] = 728218
x_original[0,0,0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

## Indexing (selecting data from tensors)

Indexing with Pytorch is similar to indexing with numpy

In [77]:
# create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [78]:
# lets a index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [79]:
#lets index in middle bracket
x[0,0]
#x[0][0]

tensor([1, 2, 3])

In [80]:
# Lets index on the most innefr barcket (last dimension)
x[0][1][1]

tensor(5)

In [81]:
# you can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [82]:
# get all values of 0th and 1st dimension but only index 1 of the 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [83]:
# get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [84]:
# get index o of 0th 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [85]:
# index on x to return 9
x[:,2,2]



tensor([9])

In [86]:
# index on x to return 3
x[:,0,2]


tensor([3])

In [87]:
# index on x return 6
x[:,1,2]

tensor([6])

## Pytorch tensor & Numpy

Numpy is a popular scientific python numerical computing library.

and because of this ,pytorch has functionality to  intercat with it.

* Data in Numpy want in Pytorch tensor -> torch.form_numpy(ndarray)

* PyTorch tensor -> Numpy -> torch.Tensor.numpy()

In [88]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
#tensor = torch.from_numpy(array).type(torch.float32)
#warning : when converting from numpy -> pytorch , pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [89]:
array.dtype

dtype('float64')

In [90]:
 #torch.arange(1.0,8.0).dtype

In [91]:
# change the value of array, what will this do to 'tensor'?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [92]:
# tensor to numpy array
tensor= torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [93]:
# change the tensor , what happens to 'numpy_tensor'
tensor = tensor +1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)

In short how a neural network learns:

start with random numbers -> tensor operations -> update random no.s to try and make them representations of the data -> again -> again p> again ...

To reduce the randomness in neural networks and Pytorch comes the concept of random seed

Esentially what the random seed does in the 'flavor' the randomness

In [94]:
import torch
# create two rand tensores
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.1729, 0.7850, 0.8444, 0.1953],
        [0.4997, 0.8155, 0.5111, 0.1662],
        [0.0103, 0.3812, 0.9596, 0.0617]])
tensor([[0.9178, 0.0989, 0.7786, 0.6516],
        [0.9859, 0.5882, 0.6345, 0.9735],
        [0.2571, 0.7856, 0.2686, 0.8072]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [95]:
# lets make rand but reproducable tensors
import torch

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)   # first tensor


torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)   # second tensor continues RNG

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and Pytorch objects on the GPUs (and making faster computations)

GPU = faster computation on nos


### 1. Getting a GPU

Easiest - User Google collab fo1 a free GPU

Use your own GPU - investment req

use cloud comuting- GCP, AWS,Azure these services allow you to rent computers on the cloud and access them

In [96]:
! nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


### 2. check GPU with Pytorch

In [97]:
# check for GPU access with Pytorch
import torch
torch.cuda.is_available()

False

In [98]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

device agnostic code

for pytorch its capable of running computeon the GPU or CPU,its best pratices to setup device agnostic code

In [99]:
# Count number of devices
torch.cuda.device_count()

0

## 3. putting tensors (and models) on the GPU

In [101]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [103]:
# move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])