<a href="https://colab.research.google.com/github/shishiradk/pytorch-pratices/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [544]:
!nvidia-smi


Sun Aug 24 05:48:37 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   38C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [545]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
print(torch.__version__)

2.8.0+cu126


introduction to tensors
creating tensor

In [546]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [547]:
scalar.ndim

0

In [548]:
#get tensor back as python int
scalar.item()

7

In [549]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [550]:
vector.ndim

1

In [551]:
vector.shape

torch.Size([2])

In [552]:
#matrix
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [553]:
MATRIX.ndim

2

In [554]:
MATRIX[1]

tensor([ 9, 10])

In [555]:
MATRIX.shape

torch.Size([2, 2])

In [556]:
#TENSOR
TENSOR = torch.tensor([[[1,2,4],
                         [2,3,4],
                         [4,5,6]]])

In [557]:
TENSOR

tensor([[[1, 2, 4],
         [2, 3, 4],
         [4, 5, 6]]])

In [558]:
TENSOR.ndim

3

In [559]:
TENSOR.shape

torch.Size([1, 3, 3])

In [560]:
TENSOR[0]

tensor([[1, 2, 4],
        [2, 3, 4],
        [4, 5, 6]])

In [561]:
TENSOR = torch.tensor([[[6,7,8],
                        [5,6,7],
                        [4,5,6]]])
TENSOR

tensor([[[6, 7, 8],
         [5, 6, 7],
         [4, 5, 6]]])

In [562]:
TENSOR.ndim

3

In [563]:
TENSOR.shape

torch.Size([1, 3, 3])

In [564]:
TENSOR[0]

tensor([[6, 7, 8],
        [5, 6, 7],
        [4, 5, 6]])

In [565]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(10,10,10)
random_tensor

tensor([[[3.4269e-01, 5.1681e-01, 6.3995e-01, 6.2074e-01, 3.6674e-02,
          8.4144e-01, 5.3270e-01, 4.2027e-01, 8.5477e-01, 9.4858e-01],
         [5.7713e-01, 4.8573e-01, 7.9220e-01, 2.8785e-01, 7.4548e-01,
          9.3990e-01, 2.3186e-02, 6.3884e-01, 9.3328e-01, 3.1255e-01],
         [4.3874e-01, 2.6530e-01, 4.5990e-01, 8.9663e-01, 2.5282e-02,
          2.0896e-01, 7.8853e-01, 3.6335e-01, 6.6079e-01, 5.1606e-01],
         [2.6370e-01, 8.2893e-01, 3.3659e-01, 1.2022e-01, 2.0949e-01,
          5.7101e-01, 5.7236e-01, 3.6985e-01, 4.7960e-01, 2.8109e-01],
         [3.1852e-01, 1.9000e-01, 6.4643e-01, 7.2122e-06, 9.3440e-01,
          3.7821e-01, 7.2834e-01, 8.5652e-01, 7.1187e-01, 6.5447e-01],
         [6.2190e-01, 9.2584e-01, 4.5308e-01, 5.8610e-01, 3.3272e-01,
          8.4700e-01, 3.8265e-01, 3.9917e-01, 8.5406e-01, 3.0082e-01],
         [9.3934e-01, 9.0293e-01, 9.4765e-01, 4.2658e-01, 1.9959e-01,
          3.0126e-01, 1.8782e-01, 9.5228e-01, 4.4143e-01, 6.9853e-02],
         [9.5

In [566]:
random_tensor.ndim

3

In [567]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224))#height,width,color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [568]:
torch.rand(3,3)

tensor([[0.3815, 0.4900, 0.0046],
        [0.3134, 0.2285, 0.7551],
        [0.0745, 0.3822, 0.5375]])

In [569]:
#zeros and ones
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [570]:
#create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [571]:
#use torch.range()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [572]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [573]:
one_to_ten.shape

torch.Size([10])

In [574]:
ten_zero = torch.zeros_like(input=one_to_ten)
ten_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor Datatype

**Note:** Tensor datatype is one of the 3 big errors you'll run into with PyTorch & deep learning:

1. Tensors not right datatype

2.Tensor not right shape

In [575]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [576]:
tensor = torch.tensor( [1.0, 2.0, 3.0],dtype=torch.float32)
print(tensor)


tensor([1., 2., 3.])


In [577]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [578]:
float_16_tensor = float_32_tensor

In [579]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [580]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [581]:
#create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8843, 0.0396, 0.3421, 0.2733],
        [0.8288, 0.6008, 0.7598, 0.9061],
        [0.1018, 0.7832, 0.2308, 0.9016]])

In [582]:
#find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.8843, 0.0396, 0.3421, 0.2733],
        [0.8288, 0.6008, 0.7598, 0.9061],
        [0.1018, 0.7832, 0.2308, 0.9016]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


###manipulating Tensors ( tensor operation)

Tensor operattion include:

*Addition

*Subtraction

*Multiplication(element-wise)

*division

*Matrix Multiplication

In [583]:
#create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [584]:
#multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [585]:
tensor

tensor([1, 2, 3])

In [586]:
#subtract
tensor - 10

tensor([-9, -8, -7])

In [587]:
#divide
tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [588]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [589]:
torch.add(tensor,10)

tensor([11, 12, 13])

Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1.Element-wise multiplication

2.Matrix multiplication(dot product)

There are two main rules that performing matrix multiplication

1. The **inner dimensions** must match:

 *(3,2) @ (3,2) won't work

 *(2,3) @ (3,2) will work

 *(3,2) @ (2,3) will work


2.The resulting matrix has the shape of the **outer dimension**:

*(2,3) @ (3,2) -> (2,2)

*(3,2) 2 (2,3) -. (3,3)




In [590]:
torch.matmul(torch.rand(10,10),torch.rand(10,10))

tensor([[1.7967, 1.3860, 1.4148, 1.8787, 2.1049, 1.4680, 1.5216, 2.3253, 1.9774,
         1.7164],
        [2.2848, 2.1588, 3.4269, 2.2727, 3.4154, 2.5794, 2.6177, 3.0346, 2.5806,
         2.9249],
        [2.1579, 1.8461, 2.0956, 1.8853, 2.3249, 2.0084, 1.9112, 2.8253, 1.8896,
         2.0470],
        [2.2893, 2.1552, 2.5952, 2.0646, 3.0490, 2.0445, 2.2808, 2.7743, 2.4763,
         2.5014],
        [2.1666, 2.0798, 2.0511, 2.2861, 2.9348, 2.3221, 2.2489, 2.9612, 2.4486,
         2.7287],
        [1.2805, 1.1399, 1.6817, 0.9401, 1.8588, 1.5722, 1.1571, 2.0312, 1.5233,
         1.4709],
        [2.7570, 2.1294, 2.7685, 2.6862, 3.4575, 2.7673, 2.5174, 3.9940, 2.9718,
         3.1618],
        [1.9600, 1.7579, 2.8912, 1.5540, 2.4248, 2.0120, 2.0623, 2.5128, 1.7410,
         2.0716],
        [2.6561, 2.4766, 3.0821, 1.9098, 3.1827, 2.6270, 2.5171, 3.0475, 2.5009,
         3.0120],
        [2.1416, 2.2106, 2.7737, 2.1867, 3.2725, 2.6452, 2.3603, 3.3980, 2.5780,
         2.4445]])

In [591]:
#Elementwise multiplication
print(tensor,"*",tensor)
print(f"Equals:{tensor * tensor}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [592]:
#matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [593]:
#matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [594]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
  print(value)



tensor(1)
tensor(5)
tensor(14)
CPU times: user 846 µs, sys: 0 ns, total: 846 µs
Wall time: 853 µs


In [595]:
tensor @ tensor

tensor(14)

In [596]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 32 µs, sys: 2 µs, total: 34 µs
Wall time: 36.5 µs


tensor(14)

### one of the most common errors in deep learning: shape errors

In [597]:
 #Shape for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])


#torch.mm(tensor_A,tensor_B) #torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A, tensor_B.T)


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [598]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor tensor

In [599]:
tensor_B,tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [600]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [601]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape} , tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying : {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
torch.matmul(tensor_A, tensor_B.T)

Original shapes: tensor_A = torch.Size([3, 2]) , tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying : torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [602]:
print(f"Original shapes : tensor_A = {tensor_A.shape} ,tensor_B = {tensor_B.shape}")
print(f"New shapes:tensorA.T = {tensor_A.shape} (same shape as above), tensor_B = {tensor_B.T.shape}")
print(f"Multiplying : {tensor_A.T.shape} @ {tensor_B.shape} <- inner dimension must match")
print("Output:\n")
out = torch.matmul(tensor_A.T, tensor_B)
print(output)

Original shapes : tensor_A = torch.Size([3, 2]) ,tensor_B = torch.Size([3, 2])
New shapes:tensorA.T = torch.Size([3, 2]) (same shape as above), tensor_B = torch.Size([2, 3])
Multiplying : torch.Size([2, 3]) @ torch.Size([3, 2]) <- inner dimension must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


Finding the min ,max , mean, sum,etc (tensor aggregation)

In [603]:
#create a tensor
x= torch.arange(1,100,10)
x , x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [604]:
# Find the main
torch.min(x) , x.min()

(tensor(1), tensor(1))

In [605]:
#Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)) ,x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [606]:
#find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min max

In [607]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [608]:
# find the position that has the min value with argminn() -> returns index position of the target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [609]:
#find the position in tensor that has the maximum value with argmax
x.argmax()

tensor(9)

In [610]:
x[9]

tensor(91)

# reshaping ,stacking , squeezing and unsquezzing tensore

* Reshaping - reshape an input tensor to a defined shape

* view  - return a view of an input tensor of certain shape but keep the same memory as the original tensor

* stacking - combine muultiple tensors on top of each other (vstack) or side by side (hstack)

* squeeze - remove all dimension from a tensor

* unsqueeze - add a dimension to a target tensor

* permute - return a view of the input with dimension permute(swapped) in a certain way

In [611]:
# lets create a tesor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [612]:
# add a extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [613]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [614]:
#changing z changes x ( because a view of a tensor shares the saame memory as the original input)
z[:,0] =5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [615]:
# stack tensors on top of eachother
x_stacked = torch.stack([x,x,x,x],dim=0 )
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

squeeze

In [616]:
#tourch.squeeze() -- remove  all single dimensions from a target tensor
print(f"previous tensor: {x_reshaped}")
print(f"previous shape: {x_reshaped.shape}")

#remove extra dimension from x_shaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew  tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
previous shape: torch.Size([1, 9])

New  tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [617]:
#tourch.unsqueeze() -- remove  all single dimensions from a target tensor
print(f"previous target: {x_squeezed}")
print(f"previous shape: {x_squeezed.shape}")

#add extra dimension from x_shaped
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew  tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape: torch.Size([9])

New  tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [618]:
#torch.permute - reaarabges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) #[height,width,color_channels]

# permute the original tensor to rearrange the axis (or dim) oredr
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2,2->0

print(f"previous shape: {x_original.shape}")
print(f"new shape: {x_permuted.shape}") #[color_channel,height,width]

previous shape: torch.Size([224, 224, 3])
new shape: torch.Size([3, 224, 224])


In [619]:
x_original[0,0,0] = 728218
x_original[0,0,0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

## Indexing (selecting data from tensors)

Indexing with Pytorch is similar to indexing with numpy

In [620]:
# create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [621]:
# lets a index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [622]:
#lets index in middle bracket
x[0,0]
#x[0][0]

tensor([1, 2, 3])

In [623]:
# Lets index on the most innefr barcket (last dimension)
x[0][1][1]

tensor(5)

In [624]:
# you can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [625]:
# get all values of 0th and 1st dimension but only index 1 of the 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [626]:
# get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [627]:
# get index o of 0th 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [628]:
# index on x to return 9
x[:,2,2]



tensor([9])

In [629]:
# index on x to return 3
x[:,0,2]


tensor([3])

In [630]:
# index on x return 6
x[:,1,2]

tensor([6])

## Pytorch tensor & Numpy

Numpy is a popular scientific python numerical computing library.

and because of this ,pytorch has functionality to  intercat with it.

* Data in Numpy want in Pytorch tensor -> torch.form_numpy(ndarray)

* PyTorch tensor -> Numpy -> torch.Tensor.numpy()

In [631]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
#tensor = torch.from_numpy(array).type(torch.float32)
#warning : when converting from numpy -> pytorch , pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [632]:
array.dtype

dtype('float64')

In [633]:
 #torch.arange(1.0,8.0).dtype

In [634]:
# change the value of array, what will this do to 'tensor'?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [635]:
# tensor to numpy array
tensor= torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [636]:
# change the tensor , what happens to 'numpy_tensor'
tensor = tensor +1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)

In short how a neural network learns:

start with random numbers -> tensor operations -> update random no.s to try and make them representations of the data -> again -> again p> again ...

To reduce the randomness in neural networks and Pytorch comes the concept of random seed

Esentially what the random seed does in the 'flavor' the randomness

In [637]:
import torch
# create two rand tensores
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8332, 0.7023, 0.4270, 0.6586],
        [0.5470, 0.4800, 0.2772, 0.1138],
        [0.4881, 0.7320, 0.1234, 0.5644]])
tensor([[0.5319, 0.3139, 0.2529, 0.8878],
        [0.9707, 0.9969, 0.5104, 0.3762],
        [0.0902, 0.1828, 0.1789, 0.6006]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [638]:
del torch   # deletes the overwritten int variable
import torch


In [639]:
# lets make rand but reproducable tensors
import torch

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)   # first tensor

# no reseed here
random_tensor_D = torch.rand(3,4)   # second tensor continues RNG

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


TypeError: 'int' object is not callable