<a href="https://colab.research.google.com/github/shishiradk/pytorch-pratices/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi


Wed Jul 23 13:26:34 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   39C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
print(torch.__version__)

2.6.0+cu124


introduction to tensors
creating tensor

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get tensor back as python int
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#matrix
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2,4],
                         [2,3,4],
                         [4,5,6]]])

In [ ]:
TENSOR

tensor([[[1, 2, 4],
         [2, 3, 4],
         [4, 5, 6]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 4],
        [2, 3, 4],
        [4, 5, 6]])

In [ ]:
TENSOR = torch.tensor([[[6,7,8],
                        [5,6,7],
                        [4,5,6]]])
TENSOR

tensor([[[6, 7, 8],
         [5, 6, 7],
         [4, 5, 6]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[6, 7, 8],
        [5, 6, 7],
        [4, 5, 6]])

In [ ]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(10,10,10)
random_tensor

tensor([[[0.4566, 0.3183, 0.8753, 0.7440, 0.5055, 0.0577, 0.3893, 0.5566,
          0.4958, 0.4048],
         [0.8919, 0.5306, 0.6406, 0.5784, 0.3862, 0.8071, 0.9076, 0.2061,
          0.4986, 0.3892],
         [0.6228, 0.2266, 0.6075, 0.3318, 0.9915, 0.2912, 0.5315, 0.9525,
          0.5075, 0.4767],
         [0.4618, 0.5280, 0.9387, 0.1817, 0.9404, 0.7746, 0.4362, 0.9234,
          0.6056, 0.8425],
         [0.1415, 0.4262, 0.4718, 0.6105, 0.1746, 0.1417, 0.1913, 0.1914,
          0.3146, 0.1997],
         [0.1656, 0.7579, 0.1991, 0.4534, 0.5311, 0.0517, 0.9327, 0.6202,
          0.8140, 0.9516],
         [0.3242, 0.9421, 0.9069, 0.7727, 0.3179, 0.4194, 0.1189, 0.2050,
          0.9712, 0.9022],
         [0.8229, 0.8667, 0.9680, 0.8100, 0.6545, 0.6694, 0.8357, 0.6611,
          0.2079, 0.0014],
         [0.3823, 0.3326, 0.8810, 0.7731, 0.2206, 0.3088, 0.9730, 0.6375,
          0.0259, 0.6757],
         [0.5692, 0.1697, 0.3294, 0.7486, 0.0455, 0.9206, 0.9073, 0.8861,
          0.0073,

In [ ]:
random_tensor.ndim

3

In [ ]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224))#height,width,color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [ ]:
torch.rand(3,3)

tensor([[0.0985, 0.5423, 0.9405],
        [0.1905, 0.3420, 0.1577],
        [0.8332, 0.9807, 0.5558]])

In [ ]:
#zeros and ones
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
#use torch.range()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
one_to_ten.shape

torch.Size([10])

In [ ]:
ten_zero = torch.zeros_like(input=one_to_ten)
ten_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor Datatype

**Note:** Tensor datatype is one of the 3 big errors you'll run into with PyTorch & deep learning:

1. Tensors not right datatype

2.Tensor not right shape

In [ ]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
tensor = torch.tensor( [1.0, 2.0, 3.0],dtype=torch.float32)
print(tensor)


tensor([1., 2., 3.])


In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor = float_32_tensor

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
#create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3937, 0.0771, 0.2478, 0.7369],
        [0.4642, 0.3062, 0.9373, 0.8911],
        [0.4442, 0.4963, 0.4625, 0.1897]])

In [ ]:
#find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3937, 0.0771, 0.2478, 0.7369],
        [0.4642, 0.3062, 0.9373, 0.8911],
        [0.4442, 0.4963, 0.4625, 0.1897]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


###manipulating Tensors ( tensor operation)

Tensor operattion include:

*Addition

*Subtraction

*Multiplication(element-wise)

*division

*Matrix Multiplication

In [ ]:
#create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
#multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
#subtract
tensor - 10

tensor([-9, -8, -7])

In [ ]:
#divide
tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])

Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1.Element-wise multiplication

2.Matrix multiplication(dot product)

There are two main rules that performing matrix multiplication

1. The **inner dimensions** must match:

 *(3,2) @ (3,2) won't work

 *(2,3) @ (3,2) will work

 *(3,2) @ (2,3) will work


2.The resulting matrix has the shape of the **outer dimension**:

*(2,3) @ (3,2) -> (2,2)

*(3,2) 2 (2,3) -. (3,3)




In [ ]:
torch.matmul(torch.rand(10,10),torch.rand(10,10))

tensor([[2.5355, 3.6605, 3.6778, 2.9050, 3.2714, 2.6683, 4.0648, 2.7982, 3.9427,
         3.1219],
        [1.3904, 2.6972, 3.2190, 1.5495, 2.7778, 2.4690, 3.2474, 2.0854, 2.8894,
         2.1152],
        [1.5680, 2.5943, 2.8926, 1.8440, 2.8670, 2.7875, 2.5317, 1.8505, 2.8341,
         2.4416],
        [1.7561, 2.5209, 2.2394, 2.0800, 2.0993, 2.0250, 2.9784, 2.1225, 2.8894,
         1.8893],
        [1.4259, 2.4367, 2.5342, 1.6172, 2.5240, 2.2767, 2.5452, 2.0142, 2.6570,
         2.1697],
        [2.1205, 3.0153, 3.4245, 2.6713, 3.2152, 2.3964, 2.9406, 2.2277, 2.9366,
         2.9531],
        [1.2314, 1.7709, 2.1925, 1.8096, 1.9314, 2.0657, 2.2188, 1.8258, 1.7225,
         1.8800],
        [2.8056, 3.8180, 3.5889, 2.7916, 3.3233, 2.4156, 4.3287, 3.0569, 4.1853,
         2.9973],
        [2.7041, 3.0615, 3.0051, 2.6503, 2.8444, 2.9617, 3.3257, 2.7203, 3.1620,
         2.5867],
        [1.6535, 2.7689, 3.0813, 2.0917, 2.9832, 2.4691, 2.7969, 2.1435, 2.8411,
         2.5043]])

In [ ]:
#Elementwise multiplication
print(tensor,"*",tensor)
print(f"Equals:{tensor * tensor}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [ ]:
#matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
#matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
  print(value)



tensor(1)
tensor(5)
tensor(14)
CPU times: user 776 µs, sys: 0 ns, total: 776 µs
Wall time: 785 µs


In [ ]:
tensor @ tensor

tensor(14)

In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 32 µs, sys: 0 ns, total: 32 µs
Wall time: 36.7 µs


tensor(14)

### one of the most common errors in deep learning: shape errors

In [ ]:
 #Shape for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])


#torch.mm(tensor_A,tensor_B) #torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A, tensor_B.T)


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor tensor

In [ ]:
tensor_B,tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape} , tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying : {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
torch.matmul(tensor_A, tensor_B.T)

Original shapes: tensor_A = torch.Size([3, 2]) , tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying : torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
print(f"Original shapes : tensor_A = {tensor_A.shape} ,tensor_B = {tensor_B.shape}")
print(f"New shapes:tensorA.T = {tensor_A.shape} (same shape as above), tensor_B = {tensor_B.T.shape}")
print(f"Multiplying : {tensor_A.T.shape} @ {tensor_B.shape} <- inner dimension must match")
print("Output:\n")
out = torch.matmul(tensor_A.T, tensor_B)
print(output)

Original shapes : tensor_A = torch.Size([3, 2]) ,tensor_B = torch.Size([3, 2])
New shapes:tensorA.T = torch.Size([3, 2]) (same shape as above), tensor_B = torch.Size([2, 3])
Multiplying : torch.Size([2, 3]) @ torch.Size([3, 2]) <- inner dimension must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


Finding the min ,max , mean, sum,etc (tensor aggregation)

In [ ]:
#create a tensor
x= torch.arange(0,100,10)
x , x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
# Find the main
torch.min(x) , x.min()

(tensor(0), tensor(0))

In [ ]:
#Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)) ,x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
#find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.argmin()

tensor(0)

to be continued